### ISSUE TITLE
no-implicit-dependencies should consider `paths` compiler option

### ISSUE THREAD

**Issue by vilchik-elena** [palantir/tslint#4083] opened 2018-07-31 08:17 UTC
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
import foo from "bar/foo";
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "error",
    "rules": {
        "no-implicit-dependencies": [true, "dev"]
    }
}
```

#### Actual behavior
```
ERROR: /Users/elena/Projects/demo/ts/main.ts[1, 17]: Module 'bar' is not listed as dependency in package.json
```

### tsconfig
```json
{
  "compilerOptions": {
    "module": "commonjs", 
    "lib": ["es2017"],
    "strict": true,

    "baseUrl": "./",
    "paths": {
      "bar/*":["src/bar/*"]
    },   
  }
}
```

#### Expected behavior
Rule should be able to look into `tsconfig` and check if imported module matches one of the `paths` mapping. I think it can be parametrised behaviour.

**Comment by jeznag** [comment] 2018-08-09 21:40
Seems to be a duplicate of https://github.com/palantir/tslint/issues/3483 Refer to solution in that thread.

**Closed** 2018-08-20 10:38 UTC
Labels: Type: Rule Enhancement

**Comment by qialex** [comment] 2020-02-12 12:14
It's not a duplicate, it should automatically white-list everything that is listed in tsconfig paths
