### ISSUE TITLE
tslint errors when parsing shorthand ambient module declarations

### ISSUE THREAD

**Issue by hellochar** [palantir/tslint#1604] opened 2016-10-05 23:44 UTC
Typescript 2.0 introduced [shorthand ambient module declarations](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#shorthand-ambient-module-declarations) that don't have a body; it seems that tslint errors when trying to parse files that contain this syntax.

### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.0.3`
- __Running TSLint via__: CLI, IntelliJ

#### TypeScript code being linted

```ts
// definition.d.ts

declare module "library/*"

```

#### Actual behavior

Tslint errors with:
```
<parent-folder>/node_modules/tslint/lib/rules/oneLineRule.js:146
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (<parent-folder>/node_modules/tslint/lib/rules/oneLineRule.js:146:17)
    at OneLineWalker.SyntaxWalker.visitNode (<parent-folder>/node_modules/tslint/lib/language/walker/syntaxWalker.js:360:22)
    at <parent-folder>/node_modules/tslint/lib/language/walker/syntaxWalker.js:453:63
    at visitEachNode (<parent-folder>/node_modules/typescript/lib/typescript.js:8251:30)
    at Object.forEachChild (<parent-folder>/node_modules/typescript/lib/typescript.js:8411:24)
    at OneLineWalker.SyntaxWalker.walkChildren (<parent-folder>/node_modules/tslint/lib/language/walker/syntaxWalker.js:453:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (<parent-folder>/node_modules/tslint/lib/language/walker/syntaxWalker.js:187:14)
    at OneLineWalker.SyntaxWalker.visitNode (<parent-folder>/node_modules/tslint/lib/language/walker/syntaxWalker.js:408:22)
    at OneLineWalker.SyntaxWalker.walk (<parent-folder>/node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (<parent-folder>/node_modules/tslint/lib/language/rule/abstractRule.js:19:16)
```

#### Expected behavior

No error

**Comment by adidahiya** [comment] 2016-10-06 04:24
dupe of #1552 & #1425

**Closed by adidahiya** 2016-10-06 04:24 UTC
