### ISSUE TITLE
"no-unnecessary-callback-wrapper" too strict when applying to functions with optional arguments

### ISSUE THREAD

**Issue by dcervelli** [palantir/tslint#3459] opened 2017-11-06 21:03 UTC
When rule `no-unnecessary-callback-wrapper` is on, 

`array.map(arg => functionWithOptionalSecondArg(arg))` 

needs to be converted into 

`array.map(functionWithOptionalSecondArg)`

These are semantically different in that the first one does not pass the array index to the function while the second one does.

Ideally, the rule would detect this condition and not trigger.

**Comment by ajafff** [comment] 2017-11-07 21:36
Duplicate of #2430

**Closed by ajafff** 2017-11-07 21:36 UTC
