### ISSUE TITLE
Feature Request: Pass multiple paths to configFile

### ISSUE THREAD

**Issue by donaldpipowitch** [palantir/tslint#2012] opened 2017-01-09 09:42 UTC
In my projects our config is placed at at least two different common places. It would be nice, if I could pass multiple paths to the `configFile` setting and if loading the first path fails the second one will be loaded and if this fails the third one will be loaded, etc. pp.

This would enable https://github.com/Microsoft/vscode-tslint/issues/158 to support more diverse projects with a single configuration, too.

**Comment by OliPro007** [comment] 2017-02-12 23:46
The plugin for ESlint has the "eslint.workingDirectories" setting (since version 1.2.5) that allows you to set an array of paths containing their own eslint config files, which is really useful when you have, for example, a client and server app in the same working group. I do not know if it is because ESlint supports that or if the behaviour is purely on the plugin's side, but being able to port that feature for TSlint would provide a huge improvement.

**Comment by adidahiya** [comment] 2017-02-14 19:07
related: cosmiconfig #1071 

that seems like a bunch of logic that doesn't necessarily belong in core tslint... I fear that we'd be bloating up the config code. how often is this feature necessary? can it just be implemented on the consumer side (i.e. in vscode-tslint)?

**Comment by JoshuaKGoldberg** [comment] 2018-11-03 23:50
+1 to not bloating TSLint core with this. Seems wasteful to reproduce cosmiconfig's logic separately.

Closing this as a subset of #1071. +1 to cosmiconfig!

**Closed by JoshuaKGoldberg** 2018-11-03 23:50 UTC
Labels: Domain: API, Type: Feature Request
