### ISSUE TITLE
name spaced config file - ie package.json

### ISSUE THREAD

**Issue by tomdavidson** [palantir/tslint#3031] opened 2017-07-11 22:53 UTC
### Proposal

tslint supports specifying a file `--config` and without will look for default tslint.json - quite nice.

It seems a somewhat trivial change to also recognize a parent object, 'tslint', in the config file so that one could pass 'config.json' or 'package.json' as the tslint config file.

```json
{
  "name": "supper-awesome",
  "tslint": {
    "extends": [
      "tslint-config-standard",
      "tslint-config-prettier"
    ],
    "rules": {
      "semicolon": false
    }
  }
}
```

config option parity with [eslint](http://eslint.org/docs/user-guide/configuring) would be pretty slick, but I just recognizing the parent object would be good enough for me.

**Comment by tomdavidson** [comment] 2017-07-11 23:17
Maybe implement https://www.npmjs.com/package/cosmiconfig ?

**Comment by thasmo** [comment] 2017-10-06 12:01
#1071 is related.

**Comment by martijnthe** [comment] 2017-11-14 11:38
+1

**Comment by JoshuaKGoldberg** [comment] 2018-11-04 09:08
Duplicate of #1071.

**Closed by JoshuaKGoldberg** 2018-11-04 09:08 UTC
