### ISSUE TITLE
Add option to `lint` method that skips file-writing

### ISSUE THREAD

**Issue by aleclarson** [palantir/tslint#4434] opened 2019-01-03 18:30 UTC
### Feature request

**Is your feature request related to a problem? Please describe.**

The `prettier-tslint` package provides a `format` function that is supposed to apply TSLint fixes to source code without any file-writing. Currently, this cannot be achieved with TSLint's API.

Related issue: https://github.com/azz/prettier-tslint/issues/26

**Describe the solution you'd like**
Add an option to the `Linter#lint` method that skips any file-writing.

**Describe alternatives you've considered**
I first looked into implementing this by looking at TSLint's source code, but a lot of the necessary functionality is contained in private methods.

**Comment by JoshuaKGoldberg** [comment] 2019-01-03 18:39
Hi @aleclarson, agreed! This looks like a duplicate of #4411.

**Closed by JoshuaKGoldberg** 2019-01-03 18:39 UTC
