### ISSUE TITLE
Max amounts of arguments before requiring object with named keys

### ISSUE THREAD

**Issue by chelmertz** [palantir/tslint#4203] opened 2018-10-04 09:01 UTC
### Rule Suggestion

Limit the amount of allowed arguments for a function, in favor of accepting an object with named keys (often an interface in typescript).

**Is your rule for a general problem or is it specific to your development style?**

Functions with long lists of arguments are much harder to compose, without resorting to function.apply() or such.

**What does your suggested rule do?**

Let's code bases embrace the code style of passing data containing objects, implementing an interface.

**List several examples where your rule could be used**

Defining a function that is called by `myFunction(a, b, c, d)` should be an error if the "max arguments" tslint option is set to something lower than 4. If the error applies, the refactoring needed should result in `myFunction({a, b, c, d})` (or `myFunction({a: something(), b: somethingElse()...})` if the variable `a` is not a variable in the calling scope).

Another example is that two functions `myFunc1({a, b})` and `myFunc2({c, d})` could both be called with a superset/union of the two argument-interfaces (`myFunc1(e); myFunc2(e)` if `e` is some API that returns `{a, b, c, d}`).

**Additional context**
Please do tell me which option to use, if this already exists. I couldn't find it by searching for "argument".

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 18:52
Duplicate of #3760

**Closed** 2018-11-05 18:53 UTC
Labels: Resolution: Duplicate
