### ISSUE TITLE
no-implicit-dependencies doesn't support absolute paths beginning with @

### ISSUE THREAD

**Issue by jeznag** [palantir/tslint#4103] opened 2018-08-07 10:56 UTC
### Bug Report
https://github.com/palantir/tslint/blob/9d7db479596c50bbf89fa87d498ab927763a6eec/src/rules/noImplicitDependenciesRule.ts#L113

means that paths beginning with `@` are not properly considered in the whitelist for no-implicit-dependencies. Using `@` at start of path is relatively common.

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted
```
import DataJunction from '@App/DataJunction';
import { Provider as I18nProvider } from '@App/I18nContext';
import RequestData from '@App/RequestData';
```

with `tslint.json` configuration:

```json
{
    "no-implicit-dependencies": [false, "dev", ["@App", "@App/Shared"]],
}
```

#### Actual behavior
linter throws error about implicit dependencies

#### Expected behavior
linter should pass

**Comment by jeznag** [comment] 2018-08-09 21:40
@eps1lon it's not. #4083 is a duplicate of #3483 This is a separate issue.

**Comment by johnwiseheart** [comment] 2018-08-09 21:43
Duplicate of https://github.com/palantir/tslint/issues/4058

**Closed by johnwiseheart** 2018-08-09 21:43 UTC
