### ISSUE TITLE
autofixing messes up function implementation.

### ISSUE THREAD

**Issue by rz-robsn** [palantir/tslint#2222] opened 2017-02-19 23:40 UTC
### Bug Report

- __TSLint version__: `4.4.2`
- __TypeScript version__: `2.2.0`
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
const stringify = (x) => {
    return JSON.stringify(x, (key, value) => {
        if (Array.isArray(value)) {
          return '[' + value
            .map((i) => {
              return '\n\t' + stringify(i);
            }) + '\n]';
        }
        return value;
      })
      .replace(/\\"/g, '"')
      .replace(/\\t/g, '\t')
      .replace(/\\n/g, '\n');
};
```

with `tslint.json` configuration:

```json
{
  "extends": "tslint:latest",
  "rules": {
    "interface-name": [false],
    "object-literal-sort-keys": false,
    "no-var-requires": false
  }
}
```

#### Actual behavior

running `tslint --fix` messes up the function implementation :

```
const stringify = (x) => {
    return JSON.stringify(x, (key, value) => {
        if (Array.isArray(value)) {
          return "[" + value
            .map((i) => {
              return ";
	" + stringify(i);;
            }) + ";
]";;
        }
        return value;
      })
      .replace(/\\"/g, '"')
      .replace(/\\t/g, "	")
      .replace(/\\n/g, "
");
};
```

#### Expected behavior

Replace the `'` characters by `"` characters for defining strings where possible, according to the `quotemark` rule :

```
const stringify = (x) => {
    return JSON.stringify(x, (key, value) => {
        if (Array.isArray(value)) {
          return "[" + value
            .map((i) => {
              return "\n\t" + stringify(i);
            }) + "\n]";
        }
        return value;
      })
      .replace(/\\"/g, '"')
      .replace(/\\t/g, "\t")
      .replace(/\\n/g, "\n");
};
```

That's it, let me know if you have any questions.

Thank you for this awesome tool :-)

**Comment by ajafff** [comment] 2017-02-20 07:57
Seems like a duplicate of #2202

**Closed** 2017-02-20 23:26 UTC
Labels: Resolution: Duplicate, Type: Bug
