### ISSUE TITLE
trailing-comma option for object literal with one key, but written over multiple lines

### ISSUE THREAD

**Issue by Zjaaspoer** [palantir/tslint#876] opened 2015-12-15 17:28 UTC
The option `singleline: always/never` seems to treat these two both as `singleline`:

```
let foo = {foo: 'bar'}
````
```
let foo = {
  foo: 'bar',
}
```
As I love this rule for keeping my code properly formatted for (irrelevant) conflict free merges I would really appreciate if I can distinguish between the two.

As the first one doesn't need a trailing comma, but the second one does.

(or am I missing something? :) )

**Comment by adidahiya** [comment] 2015-12-15 17:58
I updated your comment to what I believe was your intended formatting. Let me know if this was wrong.

Looks like a duplicate of #856

**Closed** 2015-12-16 05:54 UTC
Labels: Resolution: Duplicate

**Comment by Zjaaspoer** [comment] 2015-12-16 07:52
Indeed! You we're right with the formatting, and right about this issue being a duplicate. Sorry I didn't find that one my self :)
