### ISSUE TITLE
Running tslint with --type-check breaks in allowJs projects

### ISSUE THREAD

**Issue by Kovensky** [palantir/tslint#2568] opened 2017-04-13 09:08 UTC
### Bug Report

- __TSLint version__: 5.1.0
- __TypeScript version__: 2.3.0
- __Running TSLint via__: CLI

#### Actual behavior

Running `"$(npm bin)"/tslint -p tsconfig.json --type-check`

```
Error Cannot write file 'path/to/file.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
```

The above is printed for every single javascript file in the project, regardless of there being a .d.ts for it or not. Adding excludes does not work either.

Based on the remaining `Cannot find module` errors, it seems that the `baseUrl` option in the tsconfig is also not respected.

#### Expected behavior

No attempts to write to files other than for `--fix`, `baseUrl` to be respected.

**Comment by jiaweihli** [comment] 2017-04-19 00:18
Running into the same issue.

Specifically, with options:
  • `allowJs: false, checkJs: false`: can't import from JS files
  • `allowJS: true, checkJs: false`: same as the error in the opening post
  • `allowJS: true, checkJs: true`: doesn't terminate

It seems like tslint is trying to lint/check all js dependencies instead of only the js files that would match the config / glob.

**Comment by jiaweihli** [comment] 2017-04-19 00:20
This also affects **tslint 4.2.0**.

**Comment by jiaweihli** [comment] 2017-04-24 16:31
@adidahiya Any updates here?  This affects all projects with imported js files (e.g. `import x from './x.js'`).

There are a few rules I'd love to use, but unfortunately we have to disable all rules requiring type info at the moment.

**Comment by simonvizzini** [comment] 2017-05-24 13:44
I ran into the same problem when using the CLI. But type checking with the Webpack plugin [tslint-loader](https://github.com/wbuchwalter/tslint-loader) works somehow. Not sure if they implemented some special handling.

Only problem with tslint-loader is the really awful performance when type checking is enabled (see [tslint-loader issue here](https://github.com/wbuchwalter/tslint-loader/issues/76))

**Comment by adidahiya** [comment] 2017-05-24 16:37
this might be fixed by https://github.com/palantir/tslint/pull/2773... I haven't had a chance to look into it but maybe @ajafff does

**Comment by simonvizzini** [comment] 2017-05-24 16:49
I did some experiments with tslint myself and I believe the culprit of this issue is [here](https://github.com/palantir/tslint/blob/master/src/runner.ts#L161)

``Linter.getFileNames(program)`` will not return just ts files, but also js files, if ``allowJs`` is enabled. I think the solution is to filter out js/jsx files before linting.

**Comment by ajafff** [comment] 2017-05-24 18:03
@simonvizzini the error in the opening post is not related to tslint trying to lint those js files. The error comes from typescript trying to do some magic.
But that's another interesting issue, because tslint is not supposed to lint anything inside `node_modules` unless explicitly specified.

Regarding the "`baseUrl` is not respected" and "`exclude` does not work" that may be fixed by #2688

@adidahiya I haven't checked if #2773 fixes this. But even if it did, we should still support `--type-check` with `allowJs`.

**Comment by simonvizzini** [comment] 2017-05-24 18:30
@ajafff I'm not sure, because this is the exact same error I encountered when running tslint in combination with the ``allowJs`` ts compiler flag. And it's not about ``node_modules`` files, but own js files. We are migrating our js codebase to ts and so we import a lot of our old js files. And if I run ``tslint -p tsconfig.json --type-check`` I get the exact same error message as OP. Without ``--type-check`` there is no error.

I debugged this and one solution/workaround would be to filter out js files from the ``Linter.getFileNames`` call, because then tslint woudn't even try to lint those files. It should be investigated how tslint invokes tsc, and why it might want to try to save the output to file instead of keeping it in memory. Unfortunately I didn't have had time anymore to dig deeper.

Maybe this is common knowledge but``tsc`` and the ``allowJs`` flag is known for this ``Cannot write file 'path/to/file.js' because it would overwrite input file.`` error, I've run into it in the past. It happens because tsc "compiles" imported (own) js files to js, and then tries to save the output with the same file name. This happens when you tell tsc to write the output files alongside the ts files in the same directory. One solution is to use tsc in a away that keeps the output in memory, for example bundlers like webpack do this. Or tsc has the option to output a single bundle file iirc.

**Comment by ajafff** [comment] 2017-05-24 18:39
Typescript shouldn't compile anything when tslint is using it behind the scenes.
As this happens after `Linter.getFileNames` this can only be related to `Linter#getSourceFile` which calls `program.getSourceFile(fileName)`.

**Comment by ajafff** [comment] 2017-05-24 18:56
@simonvizzini @Kovensky @jiaweihli are you using `no-unused-variable`?

**Comment by simonvizzini** [comment] 2017-05-24 18:57
I see, but ``program.getSourceFile(fileName)`` is typescript API. Also I see now that ``Linter#lint`` explicitly allows js files as input, so I have no real clue what is going here. I'll let you guys figure this one out :smile: I just wanted to get this working so badly today that I spent some time investigating it.

**Comment by simonvizzini** [comment] 2017-05-24 18:59
@ajafff Yes, sounds like you have a clue? Let me guess, this rule will invoke tsc in a bad way somehow?

**Comment by jiaweihli** [comment] 2017-05-24 19:02
@ajafff Yes.

**Comment by jiaweihli** [comment] 2017-05-24 19:06
I can also confirm @simonvizzini's experience with `tslint-loader` - it worked, but bloated our lint time by over 100% even with 0 type-checked rules enabled.

**Comment by ajafff** [comment] 2017-05-24 19:39
Ok, found it. It's not caused by `no-unused-variable` but that rule had the same problem.
I'll submit a PR when I have the test ready.

**Comment by ajafff** [comment] 2017-05-24 19:54
Here you go #2823

**Comment by jiaweihli** [comment] 2017-05-24 20:12
Awesome.  Thanks for digging into this -

**Comment by simonvizzini** [comment] 2017-05-24 20:19
Awesome, thank you!

**Closed** 2017-05-24 22:40 UTC
Labels: Status: Needs Investigation, Type: Bug
