### ISSUE TITLE
Rule Improvement: 'ban' should be able to ban object reference

### ISSUE THREAD

**Issue by usuyama** [palantir/tslint#2290] opened 2017-03-02 22:42 UTC
#### Suggestion
Add a new option `disallow-object-reference` to [Rule: ban](https://palantir.github.io/tslint/rules/ban/) 

#### Motivation
[Rule: ban](https://palantir.github.io/tslint/rules/ban/) only catches function calls. We stumbled upon a need of catching specific object reference, which is 'self' in our case.

Without local declaration, `self` refers to `window.self`. While removing an old convention, `var self = this;`, we noticed it's prone to overlook because the compiler doesn't throw error because `self` is still valid.

**Comment by Zzzen** [comment] 2018-03-21 03:40
`window.name` is annoying too.

**Comment by NN---** [comment] 2018-06-24 17:21
Is there any solution ?
I need to disallow using a specific global object.

**Comment by Zzzen** [comment] 2018-06-25 02:40
you can ban global object If this PR is merged.

**Comment by NN---** [comment] 2018-06-26 06:42
Which PR should I vote for ?

**Comment by Zzzen** [comment] 2018-06-26 07:15
Sorry, this one. https://github.com/palantir/tslint/pull/3824

**Comment by NN---** [comment] 2018-06-26 07:43
I see the build is failing, perhaps you should fix it first.

**Comment by JoshuaKGoldberg** [comment] 2018-11-04 00:35
Duplicate of #922, which that PR addresses.

**Closed by JoshuaKGoldberg** 2018-11-04 00:35 UTC
