### ISSUE TITLE
Add Examples For Rules

### ISSUE THREAD

**Issue by ghost** [palantir/tslint#3776] opened 2018-03-15 14:03 UTC
It would be very nice to have code examples showing correct and incorrect code for the rules.

Could use ESLint docs for reference

**Comment by clemtrek** [comment] 2018-03-20 15:26
I had a look through the test codes.

It may not be a hard work to add those to the website

**Comment by aervin** [comment] 2018-03-20 16:01
@clemtrek This may be [in progress](https://github.com/palantir/tslint/pull/3602) already. Is that PR what you're after?

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 11:19
Duplicate of #1329.

**Closed by JoshuaKGoldberg** 2018-11-05 11:19 UTC
Labels: Domain: Documentation, Type: Feature Request
