### ISSUE TITLE
typedef with default param

### ISSUE THREAD

**Issue by testerez** [palantir/tslint#2194] opened 2017-02-09 05:44 UTC
### Bug Report

- __TSLint version__: `4.3.1`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: CLI  / Visual Studio

#### TypeScript code being linted
```ts
function foo(value = true) {
  // ...
}
```

#### Actual behavior

> [tslint] expected parameter: 'value' to have a typedef (typedef)

#### Expected behavior

As the type of `value` is infered from the default param, I'd like tslint to consider it valid.

**Comment by r-ohan** [comment] 2017-03-02 22:09
Having the same issue.

**Comment by nchen63** [comment] 2017-03-02 22:27
This issue isn't just with params. I see this as being a new option `allow-assignment`

**Comment by adidahiya** [comment] 2017-03-02 22:29
this is basically a duplicate of #669.
also related: #813.

**Closed** 2017-03-02 22:35 UTC
Labels: Difficulty: Easy, Status: Accepting PRs, Type: Feature Request
