### ISSUE TITLE
Set rule config inline

### ISSUE THREAD

**Issue by pburkindine** [palantir/tslint#4478] opened 2019-01-23 04:21 UTC
This is a feature request

I would love to be able to set rule options for a block of code inline, rather than just enabling/disabling the rule

Specifically, for max-file-line-count, I never ever want to disable this rule for a file (goodbye!).  When making an exception, I want to increase the cap to a new value on a per-file basis

Something like

// tslint:configure:max-file-line-count [true, 400]

// tslint:reset:some-rule

**Comment by adidahiya** [comment] 2019-01-23 18:18
duplicate of #4264

**Closed by adidahiya** 2019-01-23 18:18 UTC
