### ISSUE TITLE
Allow `Promise<void>` with `no-invalid-void`

### ISSUE THREAD

**Issue by pqnet** [palantir/tslint#4832] opened 2019-08-21 13:19 UTC
The `no-invalid-void` doesn't allow usage of `void` anywhere beside on return types. This excludes the ability to create a `Promise<void>` type, used for functions such as `async() { return; }` and in expressions such as `async(x: Promise<void>) { await x; }`

As a `Promise` represents a delayed result of a function, `void` should be allowed in the `Promise<void>` type expression in the same way it is allowed in `() => void` type expression.

It would be better to have the ability to add an exception to the rule to specify a list of generic types where `void` is allowed because it is semantically referring to a return type of a function.

**Comment by JoshuaKGoldberg** [comment] 2019-08-21 15:32
Agreed! Duplicate of #4828.

**Closed by JoshuaKGoldberg** 2019-08-21 15:32 UTC
