### ISSUE TITLE
'ngInject'; ignore option

### ISSUE THREAD

**Issue by kyranjamie** [palantir/tslint#1064] opened 2016-03-25 14:48 UTC
### Feature request

Writing TypeScript with [ng-annotate](https://github.com/olov/ng-annotate) for Angular 1.x the following code counts as a breach of:
`no-unused-expression`

```ts
export class ExampleController {
  constructor ($scope: angular.IScope) {
    'ngInject';
  }
```

Given that the string notation is required for consistent annotations in transpired languages, it'd be nice if we could add an additional rule, or modify the `no-unused-expression` to ignore this string.

We're trying to avoid writing this throughout our codebase

```ts
/*tslint:disable */ 'ngInject'; /* tslint:enable */
```

**Comment by adidahiya** [comment] 2016-03-25 16:16
duplicate of #1050

**Closed by adidahiya** 2016-03-25 16:16 UTC
