### ISSUE TITLE
Exception from tslint with template strings in className attribute in .tsx

### ISSUE THREAD

**Issue by benkopolis** [palantir/tslint#583] opened 2015-08-19 12:15 UTC
Hey, 
I encountered an intermittent exception from tslint when using template string in className attribute in tsx syntax. After some random changes and some time the exception may be gone, but not always... And I'm not getting it every time I'm using this stuff. 
This is how code looks like when tslint throws an exception exception (it doesn't help to disable / enable tslint here):
```typescript
return <div>
           <img ref="resizableImage" className={`${this.props.wrapperClassName} otherimageclass`} src={this.props.url}/>
           <div className={`resizableThumbnail ${styleName}`}/>
      </div>;
```
Below is a code with workaround, that makes tslint to work (tslint:disable doesn't work!), but I don't like it, it's not as readable and clean as a code above. 
```typescript
let cssClass: string = `${this.props.wrapperClassName} otherimageclass`;
        return <div>
                    <img ref="resizableImage" className={cssClass} src={this.props.url}/>
                    <div className={`resizableThumbnail ${styleName}`}/>
               </div>;
```
The exception I'm getting:
```
ERROR in MyFile.tsx
Module build failed: TypeError: Cannot read property 'length' of undefined
    at NoUseBeforeDeclareWalker.validateUsageForVariable (MySrcDir\node_modules\tslint-loader\node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:91:41)
    at NoUseBeforeDeclareWalker.visitVariableDeclaration (MySrcDir\node_modules\tslint-loader\node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:84:18)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48633:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48775:40)
    at MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:67
    at visitEachNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7147:30)
    at Object.forEachChild (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7305:24)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48642:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48775:40)
    at MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:67
    at visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7135:20)
    at Object.forEachChild (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7303:21)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitVariableStatement (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48439:18)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48636:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48775:40)
    at MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:67
    at visitEachNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7147:30)
    at Object.forEachChild (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7296:24)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitBlock (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48265:18)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48462:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48775:40)
    at MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:67
    at visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7135:20)
    at Object.forEachChild (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:7217:21)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48648:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitMethodDeclaration (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48364:18)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (MySrcDir\node_modules\tslint-loader\node_modules\tslint\lib\tslint.js:48561:26)
 @ ./App/MyApp.tsx 20:34-99
```
Dependencies from package.json of my tslint-loader: 
``` javascript
"dependencies": {
    "loader-utils": "^0.2.7",
    "strip-json-comments": "^1.0.2",
    "tslint": "^2.5.0-dev.2",
    "typescript": "^1.6.0-dev.20150807"
  },
```

**Comment by adidahiya** [comment] 2015-08-31 17:40
@benkopolis can you try again with the latest tslint please? we've recently made some fixes to how we handle .tsx files.

**Comment by Arcanemagus** [comment] 2015-11-02 18:20
@adidahiya here is a simple bit of code to reproduce this (in v2.5.1 at least):
```TypeScript
import {
  name as
}
```

As soon as the `as` is added to the file this is triggered.
```
C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:90
        for (var _i = 0; _i < highlights.length; _i++) {
                                        ^

TypeError: Cannot read property 'length' of undefined
    at NoUseBeforeDeclareWalker.validateUsageForVariable (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:90:41)
    at NoUseBeforeDeclareWalker.visitNamedImports (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\build\rules\noUseBeforeDeclareRule.js:69:18)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:49698:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:49900:40)
    at C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:49776:67
    at visitNode (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:7197:20)
    at Object.forEachChild (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:7471:21)
    at NoUseBeforeDeclareWalker.SyntaxWalker.walkChildren (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:49776:16)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:49770:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (C:\Users\Landon Abney\AppData\Roaming\npm\node_modules\tslint\bin\tslint-cli.js:49900:40)
```

**Comment by JKillian** [comment] 2015-11-02 19:12
@Arcanemagus We recommend code should be compilable before running tslint on the code. How are you running tslint? And have you seen the error with compilable code?

**Comment by Arcanemagus** [comment] 2015-11-02 19:38
This was reported as [an issue](https://github.com/AtomLinter/linter-tslint/issues/33) to `linter-tslint` which runs `tslint` on code as the user types.

**Comment by JKillian** [comment] 2015-11-02 21:13
Does linting as the user types normally produce good results? If it does, it might be worth trying to make the `no-use-before-decalre` rule a little more resilient to failure.

**Comment by Arcanemagus** [comment] 2015-11-02 21:17
It may show bogus lint messages (since the user is probably in the middle of writing lines), but it generally doesn't cause other linting providers to crash :wink:.

At least in the setup the user was reporting it from they can disable linting on the fly if they desire, but it seems most people leave it enabled so they don't have to wait till a save to see if there are any errors in their code.

**Comment by adidahiya** [comment] 2015-11-05 07:25
@JKillian does #763 completely address this issue?

**Comment by JKillian** [comment] 2015-11-05 16:13
@adidahiya I think so, at the very least it prevents the immediate error. With that and the changes we made to TSX handling between Aug. 19th and now, I think we're good to close this.

**Closed by JKillian** 2015-11-05 16:13 UTC
Labels: P1, Status: Needs More Info, Type: Bug
