### ISSUE TITLE
xxx.d.ts files aren't being excluded

### ISSUE THREAD

**Issue by winksaville** [palantir/tslint#2856] opened 2017-06-01 16:53 UTC
### Bug Report

- __TSLint version__: 5.4.1
- __TypeScript version__: 2.3.4
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted

Linting [Alsatian](https://github.com/alsatian-test/alsatian) using `npm run review-code` which runs tslint:
```
$ tslint './**/*.ts' --exclude './**/*.d.ts' --exclude './test/**/*.ts' --exclude './node_modules/**/*.ts'

ERROR: cli/alsatian-cli-options.d.ts[3, 14]: The class property 'fileGlobs' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[5, 14]: The class property 'timeout' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[7, 14]: The class property 'tap' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[9, 14]: The class property 'versionRequested' must be marked either 'private', 'public', or 'protected'
ERROR: cli/alsatian-cli-options.d.ts[11, 14]: The class property 'helpRequested' must be marked either 'priv
```

with `tslint.json` configuration:

```json
$ cat tslint.json
{
  "extends": "tslint:recommended",
  "rules": {
     "array-type": [true, "generic"],
     "arrow-parens": false,
     "max-classes-per-file": false,
     "one-line": [ true, "check-open-brace", "check-whitespace"],
     "trailing-comma": false,
     "variable-name": [true, "ban-keywords", "check-format", "allow-leading-underscore"],
     "ordered-imports": false,
     "object-literal-sort-keys": false
  },
  "jsRules": {
  },
  "rulesDirectory": [
  ]
}
```

#### Actual behavior

Errors are reported from `*.d.ts` files when using 5.4.1 but no errors are reported in 5.3.2:

#### Expected behavior
Should pass with 5.4.1

**Comment by winksaville** [comment] 2017-06-01 17:02
[Here](https://github.com/alsatian-test/alsatian/issues/401) is the error I created on Alastain.

**Comment by adidahiya** [comment] 2017-06-01 17:11
duplicate of https://github.com/palantir/tslint/issues/2855

**Closed by adidahiya** 2017-06-01 17:11 UTC
