### ISSUE TITLE
Getters and setters do not respect member ordering

### ISSUE THREAD

**Issue by kaba2** [palantir/tslint#4098] opened 2018-08-04 16:19 UTC
### Bug Report

- __TSLint version__: 1.0.34  (first entry in changelog)
- __TypeScript version__: 2.9.2
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
export default class A {
  protected get protectedInstanceGetter() {
    return 0
  }
  protected set protectedInstanceSetter(x: number) {}
  private get privateInstanceGetter() {
    return 0
  }
  private set privateInstanceSetter(x: number) {}
  public static staticField: number
  public static staticMethod() {}
  public constructor() {}
}
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "error",
  "extends":  ["tslint:recommended", "tslint-config-prettier"],
  "linterOptions": {
    "exclude": [
      "**/*.js"
    ]
  },
  "rulesDirectory": ["tslint-plugin-prettier"],
  "rules": {
    "prettier": true,
    "only-arrow-functions": false,
    "no-bitwise": false,

    "comment-format": [
      true, 
      "check-space"
      // Disabled: 
      // "check-lowercase"
      // "check-uppercase"
    ],
    // Lambdas of the form x => x * x
    "arrow-parens": [true, "ban-single-arg-parens"],
    "cyclomatic-complexity": [true, 666],
    "indent": [true, "spaces", 2],
    "interface-name": [true, "never-prefix"],
    "max-classes-per-file": [true, 1],
    "max-file-line-count": [true, 6666],
    "max-line-length": [true, 666],
    "member-ordering": [true, {
      "order": [
        "public-static-field",
        "public-static-method",
        "public-instance-field",
        "public-constructor",
        "public-instance-method",
        "protected-static-field",
        "protected-static-method",
        "protected-instance-field",
        "protected-constructor",
        "protected-instance-method",
        "private-static-field",
        "private-static-method",
        "private-instance-field",
        "private-constructor",
        "private-instance-method"
      ]
    }],
    "no-debugger": false,
    "no-console": false,
    "no-empty": false,
    "object-literal-sort-keys" : false,
    "quotemark": [true, "single", "avoid-escape", "avoid-template"],
    // semicolon rule conflicts with prettier
    "semicolon": false,
    "trailing-comma": [true, "never"],
    "variable-name": [true, "ban-keywords", "check-format", "allow-leading-underscore"],
    "ordered-imports": false
  }
}
```

#### Actual behavior

Some linter warnings, but none concerning the ordering of members. The getters and setters do not seem to be checked by tslint.

#### Expected behavior

The ordering of members should be public, protected, private, as specified by the configuration file. There should be linter warnings concerning wrong positions of getters and setters.

**Comment by giladgray** [comment] 2018-08-13 17:32
@kaba2 are you actually using tslint `1.0.34`?? if so, please upgrade to the latest 5.x and try again.

pretty sure this was fixed in #3984

**Comment by NaridaL** [comment] 2018-08-18 19:36
@giladgray #3984 does fix that, but it hasn't been merged. Can you take a look? If necessary I can rebase it...

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 15:59
Duplicate of #3965.

**Closed by JoshuaKGoldberg** 2018-11-05 15:59 UTC
Labels: Status: Accepting PRs, Type: Bug
