### ISSUE TITLE
Disallow boolean test on promise

### ISSUE THREAD

**Issue by burtonator** [palantir/tslint#4152] opened 2018-09-04 22:51 UTC
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

General problem.

**What does your suggested rule do?**

Prevents an always positive boolean test.

**List several examples where your rule could be used**

if you have a Promise<boolean> disallow an if test against it.

It will ALWAYS return true and is almost certainly not what you want. You almost certainly want to await it first.

This just bit me hard and I spent 2-3 hours trying to track this down before I realized my mistake.

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 16:20
Duplicate of #3983; should be better documented per #4117.

**Closed by JoshuaKGoldberg** 2018-11-05 16:20 UTC
