### ISSUE TITLE
switch-default not working?

### ISSUE THREAD

**Issue by ghost** [palantir/tslint#3559] opened 2017-12-07 15:44 UTC
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.6.2
- __Running TSLint via__: (pick one) CLI / Node.js API / VSCode / grunt-tslint / Atom / Visual Studio / etc
VSCode and CLI

#### TypeScript code being linted

```ts
// code snippet
 switch (res.status) {
            case 200:
              const json = res.json()['results'][0];
              return {
                ...json,
                stateNotSupported: json.products === undefined,
                inStoreOnly:
                  (json.products && json.products.online) === undefined,
              };
            case 204:
              return { stateNotSupported: true };
            default:
              throw new Error(`Unexpected status returned: ${res.status}`);
          }
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint:recommended",
    "tslint-immutable",
    "tslint-consistent-codestyle",
    "tslint-microsoft-contrib",
    "rxjs-tslint-rules",
    "codelyzer",
    "angular-tslint-rules",
    "tslint-config-prettier"
  ],
  "rulesDirectory": "./node_modules/codelyzer",
  "project": "./tsconfig.json",
  "exclude": [
    "**/src/**/*.ts",
    "**/e2e/**",
    "**/node_modules/**/*",
    "**/coverage/**/*"
  ],
  "format": "stylish",
  "rules": {
    "no-implicit-dependencies": false,
    "object-literal-sort-keys": false,
    "ordered-imports": false,
    "member-ordering": false,
    "no-string-literal": false,
    "radix": false,
    "no-angle-bracket-type-assertion": false,
    "no-empty": false,
    "array-type": false,
    "newline-before-return": false,
    "typedef": [
      true,
      "parameter",
      "property-declaration",
      "object-destructuring",
      "array-destructuring",
      "call-signature"
    ],
    "no-as-type-assertion": true,
    "no-var-keyword": true,
    "no-parameter-reassignment": true,
    "readonly-array": true,
    "no-mixed-interface": true,
    "insecure-random": true,
    "no-banned-terms": true,
    "no-empty-interface": true,
    "no-useless-files": true,
    "possible-timing-attack": true,
    "valid-typeof": true,
    "use-named-parameter": true,
    "arrow-return-shorthand": [true, "multiline"],
    "triple-equals": true,
    "no-unnecessary-initializer": true,
    "no-var-before-return": true,
    "no-unnecessary-qualifier": true,
    "no-unnecessary-callback-wrapper": true,
    "prefer-const": true,
    "object-literal-shorthand": true,
    "prefer-template": true,
    "no-non-null-assertion": true,
    "await-promise": true,
    "no-conditional-assignment": true,
    "no-construct": true,
    "no-for-in-array": true,
    "no-misused-new": true,
    "promise-function-async": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "no-object-literal-type-assertion": true,
    "deprecation": true,
    "no-accessor-recursion": true,
    "no-return-undefined": true,
    "no-static-this": true,
    "prefer-while": true,
    "prefer-const-enum": true,
    "no-function-expression": true,
    "parameter-properties": [true, "all-or-none"],
    "cyclomatic-complexity": [true, 10],
    "component-selector": [true, "element", "cng", "kebab-case"],
    "pipe-naming": [true, "camelCase", "sg"],
    "angular-whitespace": [true, "check-interpolation", "check-semicolon"],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-attribute-parameter-decorator": true,
    "no-input-rename": true,
    "no-output-on-prefix": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "curly": false,
    "no-inferrable-types": false,
    "use-pipe-transform-interface": true,
    "banana-in-box": true,
    "templates-no-negated-async": true,
    "use-view-encapsulation": true,
    "contextual-life-cycle": true,
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "pipe-impure": true,
    "member-access": [true, "no-public"],

    "import-blacklist": [true, "rxjs"], // ← "moment" will be added at some point

    // ↓ To be changed to `true` or unncommented, and fixed
    "no-unnecessary-class": false,
    "chai-vague-errors": false,
    "directive-selector": [
      false,
      "attribute",
      ["dir-prefix1", "dir-prefix2"],
      "camelCase"
    ],
    "variable-name": false,
    "trackBy-function": false,
    "no-forward-ref": false,
    "no-invalid-this": false,
    "underscore-consistent-invocation": false,
    "no-unused": false,
    "no-parameter-properties": false,
    "no-multiline-string": false,
    "no-void-expression": false,
    "function-name": false,
    "missing-jsdoc": false,
    "export-name": false,
    "completed-docs": false,
    "no-relative-imports": false,
    "no-stateless-class": false,
    "restrict-plus-operands": false,
    "no-increment-decrement": false,
    "mocha-no-side-effect-code": false,
    "no-floating-promises": false,
    "strict-boolean-expressions": false,
    "no-backbone-get-set-outside-model": false,
    "no-any": false,
    "no-import-side-effect": false,
    "no-unsafe-any": false,
    "no-http-string": [
      false,
      "http://www.example.com/?.*",
      "http://www.examples.com/?.*"
    ],
    "no-reserved-keywords": false,
    "early-exit": false,
    "readonly-keyword": false,
    "no-else-after-return": false,
    "no-collapsible-if": false,
    "no-unnecessary-else": false,
    "no-object-mutation": false,
    "no-magic-numbers": false,
    "no-let": false,
    "no-expression-statement": false,
    "no-this": false,
    "no-class": false
    // "rxjs-no-unused-add": { "severity": "error" },
    // "rxjs-add": { "severity": "error" },
    // "rxjs-no-patched": {
    //   "options": [{
    //     "allowObservables": ["never", "throw"],
    //     "allowOperators": false
    //   }],
    //   "severity": "error"
    // },
  }
}

```

#### Actual behavior
`ERROR: Switch statement should include a 'default' case`

#### Expected behavior
No error.

**Comment by ajafff** [comment] 2017-12-07 18:32
From your other bug requests I deduce your setup has errors. As I said in the other issue, this is most likely caused by an older version of `yarn` used to install dependencies.
You can verify that by either updating yarn or removing `node_modules` and do a fresh install with `npm` instead.

**Comment by KSuttle-cng** [comment] 2017-12-07 19:50
I've been using `yarn v1.3.2` on `node 6.10`.

**Comment by benny-medflyt** [comment] 2017-12-26 17:17
See also #3076

**Comment by JoshuaKGoldberg** [comment] 2018-11-04 10:38
Yes, duplicate of #3076.

**Closed by JoshuaKGoldberg** 2018-11-04 10:38 UTC
Labels: Type: Bug
