### ISSUE TITLE
Question: How to disallow use of anonymous js function

### ISSUE THREAD

**Issue by Alber70g** [palantir/tslint#433] opened 2015-06-12 08:47 UTC
Question: How to disallow use of anonymous js function

Say I don't want any `function() {}` in my code but only `() => {}`. How to force this (force ts-only)?

**Comment by adidahiya** [comment] 2015-06-26 16:37
we haven't implemented this rule yet, but would like to have it. duplicate of #165

**Closed** 2015-06-26 16:38 UTC
Labels: Duplicate
