### ISSUE TITLE
no-unused-variable when re-exporting

### ISSUE THREAD

**Issue by ShadowManu** [palantir/tslint#913] opened 2016-01-14 21:35 UTC
Given the following code-snippet:

```javascript
import aDefaultImport from './some-module';

export {
  aDefaultImport
}
```
tslint gives the `no-unused-variable` linter error. Shouldn't be that way AFAIK.

**Comment by JKillian** [comment] 2016-01-14 22:00
Thanks for the report @ShadowManu! This is a duplicate of #684 which should be fixed in the next nightly version of TypeScript

**Closed by JKillian** 2016-01-14 22:00 UTC
