### ISSUE TITLE
Rule trailing-comma: TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by jiripospisil** [palantir/tslint#4151] opened 2018-09-04 17:26 UTC
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.0.3
- __Running TSLint via__: CLI or VSCode

#### TypeScript code being linted

```ts
class Foo {
  bar() {
    const params = {
      {}
    };

    if (true === true) {
    }
  }
}
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "error",
  "extends": [
    "tslint:recommended"
  ]
}
```

#### Actual behavior

```bash
tslint -c tslint.json kk.ts
```

```
The 'trailing-comma' rule threw an error in 'kk.ts':
TypeError: Cannot read property 'end' of undefined
    at cb (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/tslint/5.11.0/node_modules/tslint/lib/rules/trailingCommaRule.js:163:133)
    at visitNodes (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/typescript/3.0.3/node_modules/typescript/lib/typescript.js:15129:30)
    at Object.forEachChild (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/typescript/3.0.3/node_modules/typescript/lib/typescript.js:15428:21)
    at cb (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/tslint/5.11.0/node_modules/tslint/lib/rules/trailingCommaRule.js:170:23)
    at visitNodes (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/typescript/3.0.3/node_modules/typescript/lib/typescript.js:15129:30)
    at Object.forEachChild (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/typescript/3.0.3/node_modules/typescript/lib/typescript.js:15355:24)
    at TrailingCommaWalker.walk (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/tslint/5.11.0/node_modules/tslint/lib/rules/trailingCommaRule.js:172:19)
    at Rule.AbstractRule.applyWithWalker (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/tslint/5.11.0/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.apply (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/tslint/5.11.0/node_modules/tslint/lib/rules/trailingCommaRule.js:64:21)
    at Linter.applyRule (/private/tmp/tp-20180904190451/node_modules/.registry.npmjs.org/tslint/5.11.0/node_modules/tslint/lib/linter.js:197:29)
<snip>
```

#### Expected behavior

It should not crash.

**Comment by giladgray** [comment] 2018-09-06 02:13
@jiripospisil to be fair, this is not valid javascript:
```js
const params = {
    {}
};
```

![image](https://user-images.githubusercontent.com/464822/45130950-c1f64b80-b13f-11e8-9d05-2d1aa25c9ed8.png)

**Comment by jiripospisil** [comment] 2018-09-06 08:12
> @jiripospisil to be fair, this is not valid javascript:

@giladgray  I'm aware but it's easy to get into a state which is not valid TS/JS while in the middle of changing code. 

To be clear, I'm not running TSLint manually, I'm using VSCode and it runs it automatically via [vscode-tslint](https://github.com/Microsoft/vscode-tslint).

![image](https://user-images.githubusercontent.com/20820/45143965-04aa3900-b1bd-11e8-8ebe-a7c5662eb2f3.png)

I'm fairly certain there are other ways to trigger this because I've encountered it multiple times but the provided snippet seems pretty reliable and should be enough to add some sort of a fail-safe.

**Comment by thomaspink** [comment] 2018-10-30 10:52
Same issue, any updates on this one?

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 16:19
Duplicate of #3808

**Closed by JoshuaKGoldberg** 2018-11-05 16:19 UTC
Labels: Type: Bug
