### ISSUE TITLE
Switch Statement + Curley Braces: Expected Break before Case

### ISSUE THREAD

**Issue by Think7** [palantir/tslint#898] opened 2015-12-31 13:39 UTC
The below is very valid Javascript and TypeScript however TSLint still throws the error :(

Is there something wrong with my syntax or maybe some workaround for this?

![Errrrrrrr](http://puu.sh/meOFt/4cb753d94a.png)

**Comment by JKillian** [comment] 2016-01-04 04:46
Thanks for the report @Think7! This is a duplicate of #785, so I'm going to close this. I noted that you would like this fixed over in that issue.

**Closed** 2016-01-04 04:47 UTC

**Comment by Think7** [comment] 2016-01-04 15:27
I apologize for the duplicate, missed that in my search. Thank you so much!
