### ISSUE TITLE
[feature request] - Allow for ways to ignore files and (sub)folders

### ISSUE THREAD

**Issue by rajinder-yadav** [palantir/tslint#2347] opened 2017-03-15 02:07 UTC
I would like to have a way to ignore certain files and folders.

For example, `test/` folder or test files like `*.test.ts`.

**Comment by ghostd** [comment] 2017-03-19 11:24
Duplicate of #73?

**Comment by nchen63** [comment] 2017-03-20 01:54
@rajinder-yadav Can you use the `-e` flag? If not, it will be handled in #73

**Closed by nchen63** 2017-03-20 01:54 UTC
