### ISSUE TITLE
Make semicolon rule also enforce omitting semicolons

### ISSUE THREAD

**Issue by phi2x** [palantir/tslint#542] opened 2015-08-04 07:14 UTC
In ESLint, the semi rule has an option that allows you to say "always" (enforcing semicolons) or "never" (enforce skipping semicolons).
Of course due to the ASI rules, even in "never" mode, semicolons must still be allowed to disambiguate statements beginning with [, (, /, +, or -.

As some people prefer not to use semicolons and would like to enforce that pattern, it would be nice if the semicolon rule of TSLint behaves in the same way as of the semi rule of ESLint.

For reference, here's the link to the corresponding ESLint github issue:
https://github.com/eslint/eslint/issues/618

**Comment by adidahiya** [comment] 2015-08-04 17:48
Cool, thanks for the reference to the ESLint issue. I think this is a dupe of #363. I've updated the title of that issue to make it more clear.

**Closed** 2015-08-04 17:48 UTC
Labels: Resolution: Duplicate, Type: Rule Suggestion
