### ISSUE TITLE
Having problem in installation

### ISSUE THREAD

**Issue by aammfe** [palantir/tslint#2785] opened 2017-05-18 19:50 UTC
`+-- tslint@5.2.0
| -- UNMET PEER DEPENDENCY typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev
-- UNMET PEER DEPENDENCY typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev

npm WARN tslint@5.2.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev but none was installed.
npm WARN tsutils@1.9.1 requires a peer of typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev but none was installed.`

i m using TypeScript 2.3.2 but gaving above error.

**Comment by ajafff** [comment] 2017-05-18 20:12
This may be a duplicate of #2647. Maybe you find a solution for your problem there.

**Comment by adidahiya** [comment] 2017-05-19 15:53
duplicate of https://github.com/palantir/tslint/issues/815

**Closed by adidahiya** 2017-05-19 15:53 UTC

**Comment by HonkMcFunk** [comment] 2017-07-28 17:00
I had to change the required typescript version in the `package.json`to 2.4.0 to solve this.
`"devDependencies": {
        "@ionic/app-scripts": "^1.0.0",
        "typescript": "2.4.0"
    },`

... and of course npm install afterwards.
