### ISSUE TITLE
NPM installation fails if not called against typescript

### ISSUE THREAD

**Issue by khooz** [palantir/tslint#1864] opened 2016-12-13 18:48 UTC
### Bug Report

- __TSLint version__: `Irrelevant`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: npm installation
- __Platform__: Windows
- __Node version__: 6.5.0 LTS

#### TypeScript code being linted

`npm install typescript -g` followed by `npm install tslint -g` throws an error and quits despite the fact that typescript is actually greater than 2.0.0.

If called together as `npm install tslint typescript -g`, then all is fine.

#### Actual behavior

called seperately

    `-- UNMET PEER DEPENDENCY typescript@>=2.0.0
    
    npm WARN tslint@4.0.2 requires a peer of typescript@>=2.0.0 but none was installed.

called together

    +-- tslint@4.0.2
    `-- typescript@2.1.4

#### Expected behavior

    +-- tslint@4.0.2

**Comment by adidahiya** [comment] 2016-12-13 20:39
duplicate of #815

**Closed by adidahiya** 2016-12-13 20:39 UTC
