### ISSUE TITLE
es6 module and unused variable

### ISSUE THREAD

**Issue by vasa-c** [palantir/tslint#897] opened 2015-12-28 07:54 UTC
```javascript
import a from "module";

export { a };
```

Error: `file.ts[1, 8]: unused variable: 'a'`.

Next example is OK:

```javascript
import { a } from "module";

export { a };
```

tslint 3.2.1
tsc 1.7.5

**Comment by JKillian** [comment] 2015-12-28 18:16
Thanks for the report @vasa-c! This is a duplicate of #684, so I'm going to close this issue, but I've copied your comment over to that thread so it can be easily referenced.

**Closed by JKillian** 2015-12-28 18:16 UTC
