### ISSUE TITLE
Support shorthand ambient module declarations

### ISSUE THREAD

**Issue by vvakame** [palantir/tslint#1424] opened 2016-07-22 10:01 UTC
### Bug Report

- __TSLint version__: `3.13.0`
- __TypeScript version__: `2.0.0`
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
declare module "lodash";
```

with `tslint.json` configuration:

```json
(none)
```

#### Actual behavior

```
/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/rules/oneLineRule.js:163
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/rules/oneLineRule.js:163:17)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:366:22)
    at /Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/typescript/lib/typescript.js:7959:30)
    at Object.forEachChild (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/typescript/lib/typescript.js:8117:24)
    at OneLineWalker.SyntaxWalker.walkChildren (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
    at OneLineWalker.SyntaxWalker.walk (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (/Users/vvakame/.nodebrew/node/v6.3.0/lib/node_modules/tslint/lib/language/rule/abstractRule.js:19:16)
```

#### Expected behavior

done successfully.

FYI.
this style is new feature from TypeScript 2.0.0.
https://github.com/Microsoft/TypeScript/issues/6615

We should check all of `visitModuleDeclaration` method and implement null guard to it.
I want to make a PR, but How to write the test for this issue?

**Comment by nchutchind** [comment] 2016-07-22 16:43
Ah! This looks like the issue I just submitted  #1425  where it has the same error when declaring ambient modules with a wildcard `declare module "*";`

I guess I'll just leave it and let someone on the team close or merge it.

**Comment by JKillian** [comment] 2016-07-25 15:03
Closing as a duplicate of #1425. (I know this issue was created first, but I just submitted a PR that referenced the other PR, so closing this one is easier haha)

**Closed by JKillian** 2016-07-25 15:03 UTC
