### ISSUE TITLE
disable no-trailing-whitespace for blank lines

### ISSUE THREAD

**Issue by agentschmitt** [palantir/tslint#907] opened 2016-01-12 12:48 UTC
Could the no-trailing-whitespace lint be disabled for blank lines? Mabe with an additional option?
Some code editors auto indent on new lines and its a bit annoying to have ts-lint erros for that.

**Comment by adidahiya** [comment] 2016-01-12 15:03
Duplicate of #481. I'll re-open that one since there seems to be interest in this option.

**Closed by adidahiya** 2016-01-12 15:03 UTC
