### ISSUE TITLE
TypeError: ts.forEachLeadingCommentRange is not a function

### ISSUE THREAD

**Issue by gooddaytoday** [palantir/tslint#3113] opened 2017-08-10 08:52 UTC
### Bug Report

- __TSLint version__: 5.6.0.
- __TypeScript version__: 2.4.2
- __TSUtils version__: 2.8.0
- __Running TSLint via__: (pick one)  VSCode / VSCode gulp task through "gulp-tslint" 

with `tslint.json` configuration:

```json
{
    "rules": {
        "class-name": true,
        "indent": [
            true,
            "spaces"
        ],
        "interface-name": [
            true,
            "always-prefix"
        ],
        "no-conditional-assignment": true,
        "no-console": [
            true,
            "log",
            "error",
            "debug"
        ],
        "no-debugger": true,
        "no-duplicate-variable": true,
        "no-duplicate-key": true,
        "no-unused-expression": false,
        "no-unused-new": true,
        "no-unreachable": true,
        "no-eval": true,
        "no-string-literal": true,
        "no-switch-case-fall-through": true,
        "no-trailing-whitespace": true,
        "no-unsafe-finally": true,
        "switch-default": true,
        "typedef": [
            true,
            "call-signature", 
            "property-declaration" 
        ],
        "one-line": [
            true,
            "check-open-brace",
            "check-whitespace"
        ],
        "quotemark": [
            true,
            "double",
            "avoid-escape"
        ],
        "semicolon": [
            true,
            "always"
        ],
        "typedef-whitespace": [
            true,
            {
                "call-signature": "nospace",
                "index-signature": "nospace",
                "parameter": "nospace",
                "property-declaration": "nospace",
                "variable-declaration": "nospace"
            }
        ],
        "variable-name": [
            true,
            "ban-keywords"
        ],
        "whitespace": [
            true,
            "check-branch",
            "check-decl",
            "check-operator",
            "check-separator",
            "check-type"
        ]
    }
}
```

### Stack trace and console output:

```text
Warning: ts.isWhiteSpaceSingleLine is not a function
Warning: ts.isWhiteSpaceLike is not a function
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: ts.forEachLeadingCommentRange is not a function
    at \node_modules\tsutils\util\util.js:376:16
    at iterate (\node_modules\tsutils\util\util.js:343:20)
    at Array.forEach (native)
    at iterate (\node_modules\tsutils\util\util.js:345:50)
    at Array.forEach (native)
    at iterate (\node_modules\tsutils\util\util.js:345:50)
    at Array.forEach (native)
    at iterate (\node_modules\tsutils\util\util.js:345:50)
    at forEachToken (\node_modules\tsutils\util\util.js:346:7)
    at Object.forEachComment (\node_modules\tsutils\util\util.js:374:12)
```

**Comment by jsantosh14** [comment] 2017-08-13 19:31
+1.

This issue is not occurring when I install the tslint globally and run the global command instead of local one. (On Windows). 

My commands is `tslint --fix ./src/**/*.ts`

**Comment by ajafff** [comment] 2017-08-13 20:25
There must be something wrong with your local installation.
`ts.forEachLeadingCommentRange` was introduced in typescript 2.1.0. That means there must be an older version of typescript installed. Maybe as a dependency of `gulp-tslint` which is used instead of your installed version 2.4.2

can you please post the output of `npm ls`?

**Comment by gooddaytoday** [comment] 2017-08-14 10:14
Ok, I think the problem is here (the end of list):

```
.........
| +-- through2@2.0.1
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- inherits@2.0.3
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | `-- xtend@4.0.1
| `-- xml2js@0.4.17
|   +-- sax@1.2.2
|   `-- xmlbuilder@4.2.1
|     `-- lodash@4.17.4
+-- gulp-tslint@8.1.2 extraneous
+-- gulp-typescript@2.13.6 extraneous
+-- tslint@5.3.2 extraneous
+-- tslint-language-service@0.9.6 extraneous
`-- UNMET PEER DEPENDENCY typescript@1.8.10 extraneous

npm ERR! peer dep missing: typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev, required by tslint@5.3.2
npm ERR! peer dep missing: typescript@>= 2.3.1 < 3, required by tslint-language-service@0.9.6
npm ERR! extraneous: gulp-tslint@8.1.2 R:\Client\node_modules\gulp-tslint
npm ERR! extraneous: gulp-typescript@2.13.6 R:\Client\node_modules\gulp-typescript
npm ERR! extraneous: tslint@5.3.2 R:\Client\node_modules\tslint
npm ERR! extraneous: tslint-language-service@0.9.6 R:\Client\node_modules\tslint-language-service
```

**Comment by ajafff** [comment] 2017-08-14 18:47
That's definitely the cause of the problem. TSLint requires typescript@>=2.1.0 to work.

Closing this as there is nothing we can do here.

**Closed by ajafff** 2017-08-14 18:47 UTC
Labels: External, Resolution: Not A Bug
