### ISSUE TITLE
Chalk library typings are broken

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3452] opened 2017-11-04 16:45 UTC
Chalk has now been changed to be used as a default export and bundled with its own typings; the existing DefinitelyTyped typings are therefore broken.

**Comment by ajafff** [comment] 2017-11-04 16:48
Duplicate of  #3431

**Closed by ajafff** 2017-11-04 16:48 UTC

**Comment by jez9999** [comment] 2017-11-05 11:12
Why not use my PR for the duplicate issue?  I fixed it :-)
