### ISSUE TITLE
Rule proposal: disallow `let` when `const` is applicable

### ISSUE THREAD

**Issue by buu700** [palantir/tslint#1752] opened 2016-11-19 19:02 UTC
e.g. the following code would trigger a linting error:

```
public foo () : number {
	let bar = 7;
	return bar;
}
```

But this would be fine:

```
public foo () : number {
	let bar = 7;
	++bar;
	return bar;
}
```

**Comment by adidahiya** [comment] 2016-11-20 00:09
duplicate of #491

**Closed by adidahiya** 2016-11-20 00:09 UTC
