### ISSUE TITLE
whitespace inside object braces

### ISSUE THREAD

**Issue by giladgray** [palantir/tslint#1587] opened 2016-09-30 16:03 UTC
I would like to be able to require spaces inside the braces of single-line object definitions:

```js
{ key: value, key2: value2 }
 ^                        ^
```

perhaps this makes sense as an option on the `whitespace` rule? `"check-object"`?

**Comment by adidahiya** [comment] 2016-09-30 18:25
duplicate of #1044

**Closed by adidahiya** 2016-09-30 18:25 UTC
