### ISSUE TITLE
Fix style violations automatically

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#948] opened 2016-01-27 03:48 UTC
Similar to ESLint's `--fix` option, it would be great if we could fix simple style violations.

This is a pretty large task and would likely benefit from the syntax tree transformation API enhancements coming in TypeScript 2.0 (see [here](https://github.com/Microsoft/TypeScript/issues/5595)).

**Comment by JKillian** [comment] 2016-02-05 02:11
Duplicate of #561

**Closed by JKillian** 2016-02-05 02:11 UTC
Labels: Compiler: v2.0, Difficulty: Hard, Status: Needs Proposal, Type: Feature Request
