### ISSUE TITLE
Switch return error lint

### ISSUE THREAD

**Issue by Serginho** [palantir/tslint#1815] opened 2016-12-03 00:56 UTC
**TypeScript Version:**  2.0.3 (tslint: 3.13.0)

**Code**

```ts
switch(foo){
case 0:
if(condition){
return 'something1';
else{
return 'something2';
}
case 1:
//Some code
}

```

**Expected behavior:**
Pass lint with no errors
**Actual behavior:**
TsLint error: expected a 'break' before 'case'. This's not happen if you use only return instead if clause, like:

```ts
// This pass lint inspection
case 0:
return 'something1';
case 1:
//Some code
```

**Comment by IllusionMH** [comment] 2016-12-03 23:48
Seems like duplicate of #950

**Comment by ajafff** [comment] 2017-09-02 19:42
This has been fixed some time ago by #2218

**Closed by ajafff** 2017-09-02 19:42 UTC

**Comment by omerson** [comment] 2017-12-21 12:19
```
switch(foo){
case 0:
if(condition){
return 'something1';
}
return 'something2';
case 1:
//Some code
}
```
Should work fine
