### ISSUE TITLE
Feature request: add --fix option

### ISSUE THREAD

**Issue by erikvullings** [palantir/tslint#848] opened 2015-12-02 10:28 UTC
TSlint generates many warnings for things that would be easy to fix automatically, such as missing whitespace, superfluous whitespace, e.g. at the end of a sentence, double vs single quotes, missing semi colons, missing braces around single line statements, etc. Is there an option to fix these automatically, or could you add such an option? JSCS, for example, provides such an option.

**Comment by myitcv** [comment] 2015-12-02 10:30
Dupe of https://github.com/palantir/tslint/issues/561 I think

**Comment by JKillian** [comment] 2015-12-02 19:57
Yep, is a duplicate - @erikvullings feel free to comment on #561 in support of it

**Closed by JKillian** 2015-12-02 19:57 UTC
