### ISSUE TITLE
A path in an 'extends' option must be relative or rooted, but 'tslint:all' is not.

### ISSUE THREAD

**Issue by DaveXCS** [palantir/tslint#3657] opened 2018-01-16 15:19 UTC
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.6.2
- __Running TSLint via__: (pick one) CLI 

with `tslint.json` configuration:
i had this until 5.9.1 (with 5.8.0 it was no problem)
`"extends": [
    "tslint:latest"
  ],`
this will throw now this error:
`error TS5024: Compiler option 'extends' requires a value of type string.`
tried this:
`"extends": "tslint:latest",`
and got this error:
`error TS18001: A path in an 'extends' option must be relative or rooted, but 'tslint:latest' is not.`

**Comment by ajafff** [comment] 2018-01-16 15:23
Closing as duplicate of #3643. Please see that other issue for a detailed explanation.

**Closed by ajafff** 2018-01-16 15:23 UTC

**Comment by bfred-it** [comment] 2019-05-30 11:38
Hello Google user! If you're NOT using tslint, you're in the wrong place, you're looking for:

https://github.com/Microsoft/TypeScript/issues/18865

You may be running into this issue because TypeScript can't find what you're extending.

If you're trying to extend a module, e.g. `"extends": "@sindresorhus/tsconfig"`, you have to make sure it's installed where you're calling `tsc` 

- if you're calling `tsc` locally, what you're extending needs to be installed locally (`npm install @sindresorhus/tsconfig`)

Or just make sure you're calling the local `tsc`
