### ISSUE TITLE
Switch to Circle CI

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#936] opened 2016-01-25 18:06 UTC
https://circleci.com/

**Comment by JKillian** [comment] 2016-01-25 18:45
Duplicate of #902 :wink:

**Closed by JKillian** 2016-01-25 18:45 UTC
Labels: Domain: Unit Testing, P2, Type: Task

**Comment by JoshuaKGoldberg** [comment] 2017-01-19 20:33
Out of curiosity - why?

**Comment by adidahiya** [comment] 2017-01-20 06:04
it seemed a little more modern with the latest Node versions, etc.

mostly for consistency's sake though, since all our other projects use it.
