### ISSUE TITLE
false positive: no-shadowed-variable

### ISSUE THREAD

**Issue by unional** [palantir/tslint#1099] opened 2016-04-09 08:13 UTC
tslint: 3.7.1

```ts
export default function applyMixins(
    derivedCtor: new (...args: any[]) => any,
    baseCtors: Array<new (...args: any[]) => any>): void {
    // ...
    });
};
```
error: shadowed variable: 'args'

**Comment by bencoveney** [comment] 2016-08-02 15:30
Have another set of reproduction steps if it helps. Presumably the same issue:

```typescript
class MyClass { };

declare type MyConstructor = new (myVariable: any) => MyClass;

function MyFunction(constructor: MyConstructor)
{
	const myVariable = 1;
	console.log(myVariable);
}
```

**Comment by adidahiya** [comment] 2016-08-08 21:31
@bencoveney which identifier is reported as shadowed in that example?

**Comment by bencoveney** [comment] 2016-08-09 07:00
Sorry, the error message is:

`Shadowed variable: 'myVariable'`

**Comment by IllusionMH** [comment] 2016-08-14 23:58
@adidahiya, @JKillian looks like parameters from `ConstrustorType` and `FunctionType` nodes shouldn't be added to scope. What do you think on this kind of fix?

**Comment by adidahiya** [comment] 2016-08-15 15:33
@IllusionMH sounds reasonable. I assume that those syntax kinds are distinct from constructor/function declarations? i.e. this would still produce a lint failure:

```ts
function MyFunction(x: any) {
  let x: string;
      ^ Shadowed variable 'x'
}
```

**Comment by JKillian** [comment] 2016-08-17 02:27
Fixed by #1482

**Closed by JKillian** 2016-08-17 02:27 UTC
Labels: P1, Status: Accepting PRs, Type: Bug
