### ISSUE TITLE
Missing whitespace in jsdoc

### ISSUE THREAD

**Issue by marcoturi** [palantir/tslint#3264] opened 2017-09-29 06:02 UTC
### Bug Report

- __TSLint version__: 5.7.0
- __TypeScript version__: 2.3.4
- __Running TSLint via__: (pick one) CLI 

#### TypeScript code being linted

```ts
    /**
     * ...
     * @returns timer in format mm:ss
     */
```

with `tslint.json` configuration:

```json
{
    "extends": [
        "tslint:recommended"
    ],
    "rulesDirectory": [
        "node_modules/codelyzer"
    ],
    "rules": {
        // Custom
        "trailing-comma": [false, {"multiline": "always", "singleline": "never"}],
        "interface-name": [false, "always-prefix"],
        // General
        "no-console": [true,
            "time",
            "timeEnd",
            "trace"
        ],
        "max-line-length": [
            true,
            150
        ],
        "max-classes-per-file": [false],
        "no-string-literal": false,
        "no-use-before-declare": true,
        "object-literal-sort-keys": false,
        "ordered-imports": false,
        "new-parens": false,
        "quotemark": [
            true,
            "single",
            "avoid-escape"
        ],
        "variable-name": [
            true,
            "allow-leading-underscore",
            "allow-pascal-case",
            "ban-keywords",
            "check-format"
        ],
        // Angular 2
        "angular-whitespace": [true, "check-interpolation", "check-pipe", "check-semicolon"],
        "banana-in-box": true,
        "templates-no-negated-async": true,
        "directive-selector": [true, "attribute", "am", "camelCase"],
        "component-selector": [true, "element", "am", "kebab-case"],
        "use-input-property-decorator": true,
        "use-output-property-decorator": true,
        "use-host-property-decorator": true,
        "no-attribute-parameter-decorator": true,
        "no-input-rename": true,
        "no-output-rename": true,
        "no-forward-ref": true,
        "use-view-encapsulation": false,
        "use-life-cycle-interface": true,
        "use-pipe-transform-interface": true,
        "pipe-naming": [true, "camelCase", "am"],
        "component-class-suffix": false,
        "directive-class-suffix": true,
        "templates-use-public": true,
        "no-access-missing-member": false,
        "invoke-injectable": true,
        "template-to-ng-template": true
    }
}

```

#### Actual behavior
I get "missing whitespace" on "mm:ss". Tslint complains even on dates like "1994-12-15T13:47:00" in comments.
#### Expected behavior
Not complaining about the missing space.

**Comment by ajafff** [comment] 2017-09-29 06:35
Duplicate of #3251

**Closed by ajafff** 2017-09-29 06:35 UTC
