### ISSUE TITLE
Improve file-name-casing rule

### ISSUE THREAD

**Issue by yordis** [palantir/tslint#4220] opened 2018-10-12 08:14 UTC
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

Working on the React community is common to find two patterns when it comes to the naming convention.

1. Component definition files are use PascalCase
2. Otherwise, use camelCase

**What does your suggested rule do?**

Add a configuration to `file-name-casing` rule where allow us to define the rules apply for this cases

**List several examples where your rule could be used**

```json
"file-name-casing" [true, { "jsx": "pascal-case", "all": "camel-case" }]
```

**Additional context**

**Comment by yordis** [comment] 2018-11-12 12:52
Thinking on top of my head, either we could enforce only on `jsx` or we could expect a configuration with a Regex like a syntax.

```
{
    "rules": {
        "file-name-casing": [true, {
          ".component.ts": "pascal-case",
          ".ts": "camel-case"
        }]
    }
}
```

From top to bottom, the first one that matches.

**Comment by JoshuaKGoldberg** [comment] 2018-11-12 22:16
Whoops, duplicate of #4071.

**Closed by JoshuaKGoldberg** 2018-11-12 22:16 UTC
Labels: Difficulty: Easy, Status: Accepting PRs, Type: Rule Enhancement
