### ISSUE TITLE
Rxjs "of" operator really deprecated?

### ISSUE THREAD

**Issue by BrummbQ** [palantir/tslint#4676] opened 2019-04-23 11:03 UTC
### Bug Report

- __TSLint version__: 5.16.0
- __TypeScript version__: 3.2.4
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
import { of } from 'rxjs'

of({})
```

with `tslint.json` configuration:

```json
{
  "rulesDirectory": ["node_modules/codelyzer"],
  "rules": {
    "arrow-return-shorthand": true,
    "callable-types": true,
    "class-name": true,
    "comment-format": [true, "check-space"],
    "curly": true,
    "deprecation": {
      "severity": "warn"
    },
    "eofline": true,
    "forin": true,
    "import-blacklist": [true, "rxjs/Rx"],
    "import-spacing": true,
    "indent": [true, "spaces"],
    "interface-over-type-literal": true,
    "label-position": true,
    "max-line-length": [true, 160],
    "member-access": false,
    "member-ordering": [
      true,
      {
        "order": ["static-field", "instance-field", "static-method", "instance-method"]
      }
    ],
    "no-arg": true,
    "no-bitwise": false,
    "no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-super": true,
    "no-empty": false,
    "no-empty-interface": true,
    "no-eval": true,
    "no-inferrable-types": [true, "ignore-params"],
    "no-misused-new": true,
    "no-non-null-assertion": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-string-throw": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unnecessary-initializer": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "no-use-before-declare": false,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [true, "check-open-brace", "check-catch", "check-else", "check-whitespace"],
    "ordered-imports": true,
    "prefer-const": true,
    "quotemark": [true, "single"],
    "radix": false,
    "triple-equals": [true, "allow-null-check"],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "unified-signatures": true,
    "variable-name": false,
    "whitespace": [true, "check-branch", "check-decl", "check-operator", "check-separator", "check-type"],
    "directive-selector": [true, "attribute", "rg", "camelCase"],
    "component-selector": [true, "element", "rg", "kebab-case"],
    "no-output-on-prefix": true,
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "component-class-suffix": true,
    "directive-class-suffix": true
  }
}

```

#### Actual behavior
tslint reports "of" is deprecated:
```
test-tslint.ts:3:1 - of is deprecated: use {@link scheduled} instead `scheduled([a, b, c], scheduler)`
```
#### Expected behavior
there should be no deprecation warning

**Comment by JoshuaKGoldberg** [comment] 2019-04-23 13:24
Yes, some overloads of `of` are deprecated: https://github.com/ReactiveX/rxjs/blob/f57e1fc287590b6e20ffe2d6b1b9685068b21cdf/src/internal/observable/of.ts

```
/** @deprecated use {@link scheduled} instead `scheduled([a, b, c], scheduler)` */
```

Otherwise a duplicate of #4522. Good catch!

**Closed by JoshuaKGoldberg** 2019-04-23 13:24 UTC
