### ISSUE TITLE
`no-use-before-declare` on import names

### ISSUE THREAD

**Issue by ShadowManu** [palantir/tslint#890] opened 2015-12-21 18:26 UTC
Given the following snippet
```
import {Model as BModel, Collection as BCollection} from 'bookshelf';
import {Model, Collection} from './bookshelf-extras';
```

The linter bugs about using the `Model` and `Collection` bindings on line 1 before being declared on line 2. The workaround is flipping the order between the 2, but I believe this is still a bug, since both bindings are not directly related (at least not by language rules).

**Comment by JKillian** [comment] 2015-12-22 04:24
Hi @ShadowManu, thanks for the bug report! This is essentially a duplicate of #778 so I'm going to close this issue.

**Closed by JKillian** 2015-12-22 04:24 UTC
