### ISSUE TITLE
fixer is needed for indent rule

### ISSUE THREAD

**Issue by vajahath** [palantir/tslint#3070] opened 2017-07-25 06:12 UTC
#### Feature request
`--fix`er is needed for rule [indent](https://palantir.github.io/tslint/rules/indent/).
eslint [has fixer](http://eslint.org/docs/rules/indent) for indent rule and is terribly handy!

**Comment by adidahiya** [comment] 2017-07-26 04:26
duplicate of #2814

**Closed by adidahiya** 2017-07-26 04:26 UTC
