### ISSUE TITLE
new rule: Array.concat result not assigned

### ISSUE THREAD

**Issue by HamletDRC** [palantir/tslint#229] opened 2014-10-16 09:33 UTC
var myObject = {}; 
   var myArray = []; 
   myArray.concat(myObject); // should trigger violation
   
   var myCopy = myArray.concat(myObject); // should *not* trigger violation

concat does not modify the left hand side of the method call expression. It returns a new value.

**Comment by JKillian** [comment] 2016-02-05 01:49
:+1: I forget to do this sometimes as well. @HamletDRC maybe this would make a good rule for https://github.com/Microsoft/tslint-microsoft-contrib :)

**Comment by alexeagle** [comment] 2016-08-18 00:48
I think this is a dupe of #1154

**Comment by JKillian** [comment] 2016-08-18 14:57
Closing this version, as #1154 has more extensive comments.

**Closed by JKillian** 2016-08-18 14:57 UTC
Labels: Type: Enhancement, Type: Rule Suggestion
