### ISSUE TITLE
Whitespace rule should flag spaces around `new`

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#3568] opened 2017-12-11 04:47 UTC
```typescript
const instance =    new      MyClass();
```

That feels morally wrong.

**Comment by ajafff** [comment] 2017-12-11 13:04
This is basically a duplicate of #3548 and probably many others.
I think you should rather use a formatter than a lint rule.

**Closed** 2017-12-11 15:06 UTC
