### ISSUE TITLE
`prefer-const` rule can be not suggested to variables whose value is changed by dot notation, to increase the readability.

### ISSUE THREAD

**Issue by 49-22** [palantir/tslint#4441] opened 2019-01-07 11:18 UTC
### Rule Suggestion
`const pi = 3.14;` // perfectly readable indicating its value is const and not going to change.

`const obj = {a:3};` // `obj` is const and feels like its value is not going to change.
`obj.a = 4;` //  but as this is not re-assigning and we are the value, so JS allows it. 

Can we disable rule for this kind of re-assignment?

**Is your rule for a general problem or is it specific to your development style?**
it is general problem and helps a reader to understand more.

**What does your suggested rule do?**
Do not show `prefer-const` tslint error for variables which are actually declared as `let` by developer.

**Comment by JoshuaKGoldberg** [comment] 2019-01-07 11:51
Duplicate of #4343.

`const obj` only refers to the `obj` variable not being reassigned to a different value. It doesn't have any opinion on whether `obj`'s members can be reassigned. 

If you want your values to be immutable, consider adopting rules from [tslint-immutable](https://www.npmjs.com/package/tslint-immutable).

**Closed by JoshuaKGoldberg** 2019-01-07 11:51 UTC
