### ISSUE TITLE
The 'naming-convention' rule threw ts.unescapeIdentifier is not a function

### ISSUE THREAD

**Issue by 0815fox** [palantir/tslint#4266] opened 2018-11-05 13:25 UTC
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.6
- __Running TSLint via__: CLI

```
The 'naming-convention' rule threw an error in '/home/mkr/work/twms/twms-backend/src/gen/EndPoints_Devicegroups.ts':
TypeError: ts.unescapeIdentifier is not a function
    at Object.getIdentifierText (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/util.js:872:15)
    at UsageWalker._handleDeclaration (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:667:44)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:577:27)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16128:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16124:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNodes (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15788:30)
The 'naming-convention' rule threw an error in '/home/mkr/work/twms/twms-backend/src/gen/EndPoints_Devices.ts':
TypeError: ts.unescapeIdentifier is not a function
    at Object.getIdentifierText (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/util.js:872:15)
    at UsageWalker._handleDeclaration (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:667:44)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:577:27)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16128:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16124:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNodes (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15788:30)
The 'naming-convention' rule threw an error in '/home/mkr/work/twms/twms-backend/src/settings/ReadSerialNumber.ts':
TypeError: ts.unescapeIdentifier is not a function
    at Object.getIdentifierText (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/util.js:872:15)
    at UsageWalker._handleDeclaration (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:667:44)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:577:27)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16128:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16124:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNodes (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15788:30)
The 'naming-convention' rule threw an error in '/home/mkr/work/twms/twms-backend/src/gen/EndPoints_Settings.ts':
TypeError: ts.unescapeIdentifier is not a function
    at Object.getIdentifierText (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/util.js:872:15)
    at UsageWalker._handleDeclaration (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:667:44)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:577:27)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16128:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16124:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNodes (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15788:30)
The 'naming-convention' rule threw an error in '/home/mkr/work/twms/twms-backend/src/gen/WebSocketAPIDispatcher.ts':
TypeError: ts.unescapeIdentifier is not a function
    at Object.getIdentifierText (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/util.js:872:15)
    at UsageWalker._handleDeclaration (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:667:44)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:577:27)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16128:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16124:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNodes (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15788:30)
The 'naming-convention' rule threw an error in '/home/mkr/work/twms/twms-backend/src/TWMSBackend.ts':
TypeError: ts.unescapeIdentifier is not a function
    at Object.getIdentifierText (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/util.js:872:15)
    at UsageWalker._handleDeclaration (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:667:44)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:577:27)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16128:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNode (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15779:24)
    at Object.forEachChild (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:16124:21)
    at cb (/home/mkr/work/twms/twms-backend/node_modules/tslint-consistent-codestyle/node_modules/tsutils/util/usage.js:596:23)
    at visitNodes (/home/mkr/work/twms/twms-backend/node_modules/typescript/lib/typescript.js:15788:30)
```

#### TypeScript code being linted

Cannot tell, the error message does not tell me and the file is big...

with `tslint.json` configuration:

```json
"naming-convention": [
            true,
            // forbid leading and trailing underscores and enforce camelCase on EVERY name. will be overridden by subtypes if needed
            {"type": "default", "format": "camelCase", "leadingUnderscore": "forbid", "trailingUnderscore": "forbid"},
            // require all global constants to be camelCase or UPPER_CASE
            // all other variables and functions still need to be camelCase
            {"type": "variable", "modifiers": ["global", "const"], "format": ["camelCase","UPPER_CASE"]},
            // override the above format option for exported constants to allow only UPPER_CASE
            {"type": "variable", "modifiers": ["export", "const"], "format": "UPPER_CASE"},
            // require exported constant variables that are initialized with functions to be camelCase
            {"type": "functionVariable", "modifiers": ["export", "const"], "format": "camelCase"},
            // allow leading underscores for unused parameters, because `tsc --noUnusedParameters` will not flag underscore prefixed parameters
            // all other rules (trailingUnderscore: forbid, format: camelCase) still apply
            {"type": "parameter", "modifiers": "unused", "leadingUnderscore": "allow"},
            // exclicitly disable the format check only for method toJSON
            {"type": "method", "filter": "^toJSON$", "format": null},
            // enforce UPPER_CASE for all public static readonly(!) properties
            {"type": "property", "modifiers": ["static"], "format": ["camelCase","UPPER_CASE"]},
            // enforce PascalCase for classes, interfaces, enums, etc. Remember, there are still no underscores allowed.
            {"type": "type", "format": "PascalCase"},
            // interface names must start with "I". The following part of the name must be valid PascalCase
            {"type": "interface", "prefix": "I"},
            // enum members must be in PascalCase. Without this config, enumMember would inherit UPPER_CASE from public static const property
            {"type": "enumMember", "format": "PascalCase"}
        ]
```

#### Actual behavior
prints exception

#### Expected behavior
Should not print exception like before updating typescript to version 3.x

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 13:28
👋 @0815fox, thanks for posting this! Your issue is fixed in the latest versions of the `tsutils` package. Update that and the errors should go away.

Duplicate of #4016.

**Closed by JoshuaKGoldberg** 2018-11-05 13:28 UTC

**Comment by 0815fox** [comment] 2018-11-05 13:34
Shouldn't updating tslint also have forced an update for that package?

I already had found the issue you linked above, however, that issue does not tell me, that this issue here was fixed as well (and especially it does not really tell me how). That's why I opened this issue as suggested in this comment: https://github.com/palantir/tslint/issues/4016#issuecomment-418675398

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 13:37
> Shouldn't updating tslint also have forced an update for that package

Unfortunately no; `tsutils` is a peer dependency. How are you running TSLint? If you're running it on the CLI like `tslint -c tslint.json ...`, you might have to `npm update tsutils --global` to update it globally.
