### ISSUE TITLE
Indent rule not reporting or fixing indent size violations

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#2814] opened 2017-05-23 04:42 UTC
### Bug Report

- __TSLint version__: 5.3.2
- __TypeScript version__: 2.3.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
export function foo() {
  return 123;
}
```

with `tslint.json` configuration:

```json
{
  "extends": ["tslint:latest"],
  "rules": {
    "indent": {
      "options": ["spaces", 4]
    }
  }
}
```

#### Actual behavior

No errors with `tslint`. No fixes with `tslint --fix`.

#### Expected behavior

Errors reported with `tslint`, fixes applied with `tslint --fix` so that the resulting file looks like:

```ts
export function foo() {
    return 123;
}
```

---

#2723 did not quite work like I expected. The problem seems to be that a failure is only reported if using the wrong whitespace character, not if the indent size is off (like in my example). [relevant source](https://github.com/palantir/tslint/blob/faaee3970445c0ec636cd2b5c8600d2b81f0b035/src/rules/indentRule.ts#L193).

**Comment by glen-84** [comment] 2017-05-27 08:47
@adidahiya See [this comment](https://github.com/palantir/tslint/issues/581#issuecomment-300765558) by @nchen63.

**Comment by dolanmiu** [comment] 2017-05-28 17:29
From @nchen63:

> It fixes tabs -> x spaces and x spaces -> tabs, but doesn't fix x spaces -> y spaces

It SHOULD do `x spaces` to `y spaces` though.

**Comment by ladjzero** [comment] 2017-06-15 07:21
My project uses both 2 and 4 spaces. Fix rule `x spaces` to `y spaces` would be very useful.

**Comment by hodavidhara** [comment] 2017-07-10 22:05
I also ran into this issue expecting it to fix size violations, or at least report them as errors so that I can fix them. At the moment it seems the configuration for the indent size documented on the site (https://palantir.github.io/tslint/rules/indent/) doesn't actually do anything.

**Comment by rsheptolut** [comment] 2017-07-16 14:40
Yes, please fix this bug. Angular CLI uses 2 spaces for an indentation level when generating a file or a project, and all quotes are single quotes. Then it runs tslint to fix these according to the user's tslint.json. Quotes work well (transforming to double quotes as per my preference), but indentation stays at 2 spaces (while I prefer 4). Tslint only reports an error if it sees an actual TAB character, but seems reasonable that it should also check the number of spaces

**Comment by Omniroot** [comment] 2017-07-19 16:56
It seems to me like the implementation being used in https://github.com/palantir/tslint/blob/master/src/rules/indentRule.ts is quite naive, and I wouldn't expect it to work for `x spaces -> y spaces`. The approach seems to be fine with tabs, based on the comment here, but I can't see this approach as viable for spaces.

Say, for instance, an indentation width of 2 spaces was chosen, and consider this code:
```
foo = {
    a: {
  b: {
    c: 'c'
  }
    },
    d: 'd'
}
```

How would our current implementation know to fail this at all? Each sequence of spaces passes the regex `/  /`. Even if we looked for multiples of 2 spaces, this would pass. Similarly, in multi-level indentation scenarios, 4 leading spaces could be a passing scenario, whereas beginning a single level of indentation with 4 spaces should fail.

I think any solution would need to traverse the AST, similar to what eslint does (https://github.com/eslint/eslint/blob/master/lib/rules/indent.js). The downside of that would be that we'd take a slight performance hit for `tabs -> spaces` or `spaces -> tabs`. We could get around that by choosing the implementation based on the settings, but I anticipate that the current implementation will fail if a combination of tabs and spaces are used, in which case we should only use the AST-based solution.

I think that at least some of the AST work done in the eslint implementation can be handled by typescript's library directly, so the solution shouldn't be too hard to write up.

**Comment by adidahiya** [comment] 2017-07-19 17:05
> How would our current implementation know to fail this at all?

It doesn't _technically_ need to. The `align` rule would prevent you from writing code like that. Sure, we could walk the AST in the `indent` rule as well. All I care about is that some combination of `indent` and `align` allow me to accomplish what I wrote in the issue description.

**Comment by Omniroot** [comment] 2017-07-19 17:07
> The align rule would prevent you from writing code like that.
Nice! I missed that when I was examining the source code. I'll take a peak over there too. TBH, I kinda like the idea of leveraging existing rules to keep others as naive as possible.

**Comment by johnwest80** [comment] 2017-07-19 17:22
I'm experiencing the same issue.  The rule below will catch tabs being used instead of spaces, but won't catch an incorrect number of spaces.  I can change 2 to any other number, and I still get no errors.  I'm using tslint 5.5.0.

    "indent": [true, "spaces", 2],

**Comment by JeremyCraigMartinez** [comment] 2017-07-26 17:56
Why was this closed? It seems like it still isn't working as expected

**Comment by mDibyo** [comment] 2017-08-30 18:46
Any updates on this? (If someone isn't working on a fix already, I'm willling to give it a go. )

**Comment by adidahiya** [comment] 2017-08-30 19:38
@mDibyo go for it

**Comment by fmflame** [comment] 2017-09-04 21:25
+1

**Comment by jscharett** [comment] 2017-09-19 17:15
@mDibyo Have you made any progress on this?

**Comment by mDibyo** [comment] 2017-09-21 05:46
I have a partial implementation. Will try to complete it and put up a PR over the weekend

**Comment by adidahiya** [comment] 2017-09-21 14:27
Just wanted to give a heads up that this issue has become a lower priority for me since I've started to use prettier formatting with [tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier) for my projects. We might try to add more official support for prettier in the built-in configs in the future and correspondingly adjust focus to core rules that are not formatting-related.

**Comment by glen-84** [comment] 2017-09-24 09:00
> Prettier, on the other hand, strives to fit the most code into every line.

What if you don't want that?

> With the print width set to 120, prettier may produce overly compact, or otherwise undesirable code.

We use 120 characters in our projects.

---

Also, it's yet another dependency. I think that I'd prefer to just use regular TSLint rules.

**Comment by adidahiya** [comment] 2017-09-25 16:23
> I think that I'd prefer to just use regular TSLint rules.

@glen-84 yeah, that's fine, which is why i'm not saying we should remove all formatting rules from TSLint and delegate completely to an external formatter. Prettier is obviously opinionated and not everyone is going to choose to use it. This issue is still open for PRs.

**Comment by cyberhck** [comment] 2017-11-17 04:09
what's going on with this issue?

**Comment by yubaoquan** [comment] 2017-11-17 06:25
my pr is working in progress, to many cases, still need time. @cyberhck

**Comment by cyberhck** [comment] 2017-11-17 06:50
so we expect it to get merged quite soon then :slightly_smiling_face:

**Comment by jscharett** [comment] 2018-01-10 19:44
Any update here?

**Comment by aervin** [comment] 2018-01-13 14:16
Perhaps we could ask the [typescript-formatter](https://github.com/vvakame/typescript-formatter) maintainers to expose a couple APIs? The package can already verify that an entire sourcefile is formatted [according to settings in a `tslint.json` file](https://github.com/vvakame/typescript-formatter#read-settings-from-files)

However, it may need help to play nice with TSLint's fixer setup.

**Comment by szeck87** [comment] 2018-03-13 01:42
> The problem seems to be that a failure is only reported if using the wrong whitespace character, not if the indent size is off.

@adidahiya I can't get it to report an error if the wrong indentation character is used.  If I set the rule to spaces/4 and have something like:

```typescript
export function foo() {
return 123;
}
```
or
```
export function foo() {
<tab>return 123;
}
```

It doesn't report back an error.  Per your original comment, are you sure it reports it if it's the wrong whitespace character?

**Comment by sant123** [comment] 2018-03-14 15:23
Any advance on this? Just asking 😝

**Comment by pelotom** [comment] 2018-03-14 15:28
Advice? Use [Prettier](https://prettier.io).

**Comment by jscharett** [comment] 2018-03-15 00:17
Has anyone tried [tslint-eslint-rules](https://www.npmjs.com/package/tslint-eslint-rules)?

**Comment by damacisaac** [comment] 2018-03-16 16:31
@jscharett tslint-eslint-rules works with the `ter-indent` rule. Unfortunately it doesn't cover JSX indentation...

**Comment by jscharett** [comment] 2018-05-10 13:42
Any hope of a fix here?

**Comment by stifflerus** [comment] 2018-05-10 19:34
This bug is still not fixed in v5.10.0

**Comment by jhaenchen** [comment] 2018-05-11 19:18
Why is this still not fixed? Either remove the rule from the docs ("space number is an optional parameter that does nothing") or actually build it.

**Comment by aervin** [comment] 2018-05-11 19:42
I gotta say, I don't imagine TSLint will ever be able to format JS code as well as Prettier. This is a complicated problem, and Prettier has solved it better than anyone else. I don't think we should be relying on TSLint for this, especially since projects often use both tools in tandem, and conflicts will likely arise...

**Comment by jscharett** [comment] 2018-05-11 20:46
@aervin I tend to disagree here.  The 2 projects, in my opinion, have different purposes.  Prettier falls into the category of formatting while TSLint is more in line with validating.  Yes, TSLint can do formatting for some rules, but its intended purposes as a linter, goes back to validating.

The problem with relying on Prettier is that it is opinionated.  That's great is you agree with its style, but what if you don't?  We used to all use JSLint, and we all complained because it was so opinionated.  Then came JSHint and JSCS, which gave us some control.  Now we have powerful tools like @eslint which gave us the ability to plug-n-play and "fix" issues automatically.

While I am sure Prettier is a great project, I personally see it as a step backwards.  Its taking control away from me.  TSLint doesn't need to "fix" the code, if that is the issue, just flag it as an issue.  I don't doubt that this issue is complicated, but eslint solved it.  The rule used to work; what changed to break it?

**Comment by aervin** [comment] 2018-05-11 21:10
@jscharett Thanks for your congenial response. I think we agree in some respects. However, I'm confused about the "format"/"validation" distinction. Prettier doesn't validate code, it formats it. Any indentation-related problem, to me, falls outside the realm of "validation". "Indentation" is in the "formatting" realm. I like that Prettier is strictly in charge of formatting my code. I use TSLint to help me write code that makes sense on the programmatic level. So I agree that these projects have different purposes. My argument is that we should confine these projects to those purposes. Let's leave Prettier to fixing indentation problems, and let's leave TSLint to warning devs about arrow functions that can be simplified.

I also agree that Prettier is opinionated. I rather like that about Prettier. Now my team doesn't have to discuss whose formatting opinion is more reasonable. We can all complain about Prettier :laughing: .

**Comment by pelotom** [comment] 2018-05-11 21:35
>While I am sure Prettier is a great project, I personally see it as a step backwards. Its taking control away from me.

My experience was that I thought I cared about having fine-grained control over formatting rules right up until I added Prettier... and soon after I realized I didn't care so much about the particular way things were formatted, as the fact that they were formatted consistently. It's a huge cognitive load off not to worry about that any more, and concentrate entirely on what I want the code to _do_ rather than how it looks.

**Comment by stifflerus** [comment] 2018-05-12 04:36
tslint already validates other things that would fall under the category of formatting. For example, enforcing alignment, bracket style, or spaces between variable names and operators. Additionally, it is desirable to be able to validate indentation without having to rely on an opinionated solution like prettier.

**Comment by ffxsam** [comment] 2018-08-06 17:13
Needs less discussion, and more PR'ing. 😉😉

**Comment by keradus** [comment] 2018-08-06 19:52
go ahead @ffxsam

**Comment by ffxsam** [comment] 2018-08-06 19:56
My comment was mostly tongue-in-cheek. Though I'm wondering why this issue is over a year old and no progress has been made. Seems like everyone is just arguing about linting vs Prettier.

**Comment by jhaenchen** [comment] 2018-08-06 19:57
@ffxsam Because there's debate about whether tslint is more about the ts part or about the lint part

**Comment by ffxsam** [comment] 2018-08-06 19:59
That's a valid point. Seems like there's some overlap with TSLint/ESLint. But the fact remains that there's a non-working `indent` option that has been broken for who knows how long. Seems like the fastest/easiest thing would be for someone familiar with the TSLint codebase to fix it...?

**Comment by qzmfranklin** [comment] 2018-08-17 14:11
Vote up on fixing `x spaces` => `y spaces`.  This is a feature our company relies very heavily on.  It makes no sense just not fixing this.

**Comment by cyberhck** [comment] 2018-08-21 01:06
@ffxsam I'm watching this issue for almost a year now, yeah it's been long, but as you can see there are two PR attempts, and it didn't work out till now, I think it's harder than it looks, but of course for maintainers it might be easier, I just have a lot of patience :slightly_smiling_face:

**Comment by DavidMorton** [comment] 2018-08-29 17:33
Correct me if I'm wrong, but it's looking to me like the core issue here is the complete disconnect between the align and indent rules. 

https://github.com/palantir/tslint/blob/e766f517555580e155b6f58a582cff53c63563a9/src/rules/alignRule.ts#L178

Somewhere around here in the align method, it seems there should be taking some tabbing into account. 

![image](https://user-images.githubusercontent.com/2237045/44804664-97c4ec80-ab87-11e8-9250-8689698de6df.png)

This image gives a good example. I moved type: Types.UUID to the far left against the left margin, hit save, and the align rule inserted precisely three SPACES despite the fact that I have indent set to tabs. If align knows about indent, then the align rule could fix some of these issues and get us back on track.

**Comment by dimaShin** [comment] 2018-08-30 12:12
Still reproducible in the empty project
https://github.com/dimaShin/tslint-reproduce-2814

**Comment by maximelkin** [comment] 2018-10-12 11:14
@stifflerus Also rule should work with if/for/arrow function without {} blocks

**Comment by affanshahid** [comment] 2018-10-14 18:57
Would be awesome if this was fixed.

**Comment by thor84no** [comment] 2018-10-16 13:42
I can't believe something as fundamental as enforcing indentation rules is still not working.

**Comment by Diokuz** [comment] 2018-11-01 07:38
Works for me: https://github.com/eslint/typescript-eslint-parser

**Comment by yoni333** [comment] 2018-11-26 19:34
the solution i found for the indent problem in angular is to add **prettier** with the next steps:
npm install --save-dev tslint-plugin-prettier prettier tslint-jasmine-rules
tslint.json
` "rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/tslint-plugin-prettier",
    "node_modules/tslint-jasmine-rules/dist"
    
   
  ],
  "extends": "tslint-plugin-prettier",
 
  "rules": {
   "prettier": true,
//add here your wanted rules`

and in packege.json add 
" ,"prettier": {
    "singleQuote": true,
    "printWidth": 140,
    "semi": true,
    "bracketSpacing": true,
    "arrowParens": "always",
    "parser": "typescript"
  }"

**Comment by qzmfranklin** [comment] 2018-12-22 09:03
This is a functionality that almost everybody uses on a daily basis. Would appreciate if this issue gets more attention.

**Comment by hiteshaleriya** [comment] 2018-12-29 14:43
Guys, You can use [ter-indent](https://github.com/buzinas/tslint-eslint-rules/blob/master/src/docs/rules/terIndentRule.md) option provided by tslint-eslint-rules.

It works for me. Cheers!

**Comment by SpencerKaiser** [comment] 2019-01-15 16:46
@hiteshaleriya that's what I've had in my project for a while now, but it isn't actually fixing the errors, just silencing them... here's my `tslint.json`:
```
{
    "extends": "tslint-config-airbnb",
    "rules": {
        "ter-indent": ["error", "spaces", 4],
        "no-unused-vars": ["warn"],
        "no-multi-spaces": false,
        "no-console": false,
        "max-line-length": false,
        "import-name": false
    }
}

```
and here's a relevant example that finished without causing warnings or errors:
```
function retrieveAndSetConfig(): Promise<any> {
  return new Promise((resolve, _) => {
  // ^ 2 spaces, expected 4
    const ghe = new GHEUtils();
    // ^ 4 spaces, expected 8
    // ...
}
```

**Comment by hiteshaleriya** [comment] 2019-01-15 17:04
@SpencerKaiser Can you please update your ter-indent rule as shown below and then try:
```
"ter-indent": [true, 4]
```
I checked your example and it is working as expected at my end (causing errors).

**Comment by SpencerKaiser** [comment] 2019-01-15 17:14
@hiteshaleriya thanks for getting back to me so quickly! So it's now throwing errors as expected (👍) but it's not fixing any of them with `--fix`. Any ideas?

**Comment by hiteshaleriya** [comment] 2019-01-15 18:57
@SpencerKaiser Can you try running the --fix command twice. First time it will indent first line only then second time it will indent the rest (for your example code). Seems weird but please report the issue if it doesn't work.

**Comment by SpencerKaiser** [comment] 2019-01-15 20:36
@hiteshaleriya so a couple of observations... I didn't need to run it again, I needed to run it roughly `n/4` times where `n` is the length of the indentation in spaces of the farthest indented line in the project ¯\\_(ツ)\_/¯

After finally finishing them all, it seems it's skipping over basic indentation errors like this:
```
const myThing = {
    wat: 1,
 wattt: 5,    // 1 space, expected 4
};
```
Thoughts??

**Comment by shubich** [comment] 2019-01-26 23:02
[How I've solved that issue with tslint-config-prettier](https://gist.github.com/shubich/ee8ff287037783981e6511531d001163)

**Comment by SpencerKaiser** [comment] 2019-01-29 13:56
@shubich I ended up doing the same thing...

**Comment by MaKCbIMKo** [comment] 2019-03-13 16:32
Is there any update on this?

**Comment by cyberhck** [comment] 2019-03-13 16:40
@MaKCbIMKo as far as I understand, the entire team will be moving to integrate eslint visit typescript-eslint, and in near future tslint will be deprecated, so it's as good as ignoring this rule for now.

**Comment by adidahiya** [comment] 2019-03-13 17:15
Closing due to the complexity of this task and the change in project direction: #4534

**Closed** 2019-03-13 17:14 UTC
Labels: Available in ESLint, Formatting rule, P2, Resolution: Declined, Type: Bug

**Comment by linvain** [comment] 2019-03-14 15:02
Works perfectly with eslint and [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) (see #4534)
```javascript
module.exports = {
	"env": {
		"browser": true,
	},
	"parser": "@typescript-eslint/parser",
	"parserOptions": {
		"ecmaVersion": 2019,
		"sourceType": "module",
		"ecmaFeatures": {
			"jsx": true
		},
		"project": "./tsconfig.json",
	},
	"plugins": ["@typescript-eslint"],
	"rules": {
		"@typescript-eslint/indent": ["error", 2] // or ["error", "tab"]
	}
}
```

**Comment by wszgxa** [comment] 2019-05-06 06:44
So the final solution is going to use typescript-eslint ?

**Comment by thakurvijendar** [comment] 2020-03-29 15:51
> [How I've solved that issue with tslint-config-prettier](https://gist.github.com/shubich/ee8ff287037783981e6511531d001163)

Link not found.

**Comment by JoshuaKGoldberg** [comment] 2020-03-29 16:50
🤖 Beep boop! 👉  **TSLint is deprecated** 👈  and you should **switch to [typescript-eslint](https://typescript-eslint.io)**! 🤖 

🔒 This issue is being locked to prevent further unnecessary discussions. Thank you! 👋

**Comment by JoshuaKGoldberg** [comment] 2020-03-29 16:51
P.S. [tslint-config-prettier](https://github.com/prettier/tslint-config-prettier) - please stop using _linters_ such as TSLint to _format_ your TypeScript. That's better done by a _formatter_ such as [Prettier](https://prettier.io).
