### ISSUE TITLE
Add option to auto fix

### ISSUE THREAD

**Issue by ericwooley** [palantir/tslint#1023] opened 2016-03-09 17:45 UTC
eslint has a --fix option available, that can fix a lot of errors. 

I am new to tslint, so I don't know how hard this would be to implement, but it's been extremly helpful on eslint. 

(Sorry if this is a dup, it's a very hard term to search for)

**Comment by adidahiya** [comment] 2016-03-09 20:05
no worries, dupe of #561. I tried to add tags to that one to make it more discoverable :grin:

**Closed by adidahiya** 2016-03-09 20:05 UTC
