### ISSUE TITLE
Rule suggestion: no unused exports

### ISSUE THREAD

**Issue by OliverJAsh** [palantir/tslint#2579] opened 2017-04-15 20:49 UTC
TS has knowledge of where a variable or function is used in a project, so theoretically it should be possible to implement a rule to warn when an export is not used.

This would be quite useful for modules containing lots of functions (like helpers), where it's not immediately clear when they stop being used due to a refactor, for example.

What do you think? :-)

**Comment by danvk** [comment] 2017-04-24 14:09
See https://github.com/palantir/tslint/issues/780 and https://github.com/pzavolinsky/ts-unused-exports

**Comment by msuperina** [comment] 2018-09-24 11:58
#780 references this issue and is now closed. Is this issue still open or shall I use ts-unused-exports ?
Thanks in advance :)

**Comment by OliverJAsh** [comment] 2018-09-24 12:00
#780 is not closed?

**Comment by msuperina** [comment] 2018-09-24 12:06
@OliverJAsh oh apologies, I misread the Closed label on the line Feature Request: Typescript dead code cleanup #3223

**Comment by JoshuaKGoldberg** [comment] 2018-11-04 01:08
Yup, duplicate of #780. +1 to this idea!

**Closed by JoshuaKGoldberg** 2018-11-04 01:08 UTC

**Comment by karim10** [comment] 2019-06-21 12:02
you can also use `ts-purne` https://github.com/nadeesha/ts-prune, less **buggy**
