### ISSUE TITLE
no-implicit-dependencies/whitelist-with-dev tests failing on master

### ISSUE THREAD

**Issue by michaelblack** [palantir/tslint#4010] opened 2018-07-03 18:47 UTC
### Bug Report

- __TSLint version__: master 9d7db479596c50bbf89fa87d498ab927763a6eec
- __TypeScript version__: 2.8.3
- __Running TSLint via__: CLI (yarn test:rules)

#### Additional Info
Running from a freshly cloned repo on macOS 10.13.3

#### Actual behavior
```
test/rules/no-implicit-dependencies/whitelist-with-dev/test.ts.lint: Failed!
Expected (from .lint file)
Actual (from TSLint)
  import * as ts from 'typescript';
+                     ~~~~~~~~~~~~  [Module 'typescript' is not listed as dependency in package.json]

  import * from 'src/a';

  import * from 'app/b';

  import * from 'notapp/c';
                ~~~~~~~~~~  [Module 'notapp' is not listed as dependency in package.json]

error Command failed with exit code 1.
```
#### Expected behavior
```
test/rules/no-implicit-dependencies/whitelist-with-dev/test.ts.lint: Passed
```

**Comment by ajcrites** [comment] 2018-07-20 12:41
I'm not able to reproduce this; I believe this was ultimately fixed in current master.

**Comment by johnwiseheart** [comment] 2018-07-27 22:52
I believe this has been fixed.

**Closed by johnwiseheart** 2018-07-27 22:52 UTC
