### ISSUE TITLE
Allow disabling some rules on specific directory or file glob

### ISSUE THREAD

**Issue by ftdube** [palantir/tslint#3686] opened 2018-01-31 17:08 UTC
There should be a way to switch specific rules on and off for directories of fileGlobs.

For example, I want to enable the "newline-per-chained-call" rule in my code.  But applying this rule to my test directory using jasmine generates a lot of errors and the result of restructuring my unit tests to fit with this rule isn't necessarily more readable or cleaner (plus it would take a crazy amount of time).

I don't want to disable tslint altogether in my unit tests and going file by file to add tslint-disable just smells like a bad idea.

I could create a split ruleset for the test directory and run both separately, but then the tslint integration in our IDE (Webstorm) ignores the second ruleset.

It seems to me like we should be able to per-directory or fileGlob rulesets and/or be able to say that a specific rule should be turned off for specific directory or fileGlob.

**Comment by ajafff** [comment] 2018-02-01 14:19
Duplicate of #3447

**Closed by ajafff** 2018-02-01 14:19 UTC
Labels: Resolution: Duplicate
