### ISSUE TITLE
error TS5024: Compiler option 'extends' requires a value of type string

### ISSUE THREAD

**Issue by gdereese** [palantir/tslint#3685] opened 2018-01-31 01:06 UTC
### Bug Report

- TSLint v5.9.0
- TypeScript v2.6.2
- Running TSLint via Node.js API

#### TypeScript code being linted

n/a

with `tslint.json` configuration:

```json
{
  "extends": ["tslint:recommended", "tslint-config-prettier"],
  "rules": {
    "no-console": false
  }
}
```

#### Actual behavior
The following error message is displayed:
```
error TS5024: Compiler option 'extends' requires a value of type string.
```

#### Expected behavior
TSLint processes the source code.  Note, this scenario appears to work with TSLint v5.8.0, but stopped working after upgrading TSLint to v5.9.0.

**Comment by adidahiya** [comment] 2018-01-31 15:30
duplicate of #3643

**Closed by adidahiya** 2018-01-31 15:30 UTC
