### ISSUE TITLE
Why is "I" prefix interface-name default?

### ISSUE THREAD

**Issue by mellis481** [palantir/tslint#4199] opened 2018-10-03 15:35 UTC
I'm not sure if a "feature request" is the proper ticket type to raise this issue on Github.  Nonetheless, I would like to know why the default for the [interface-name](https://palantir.github.io/tslint/rules/interface-name/) rule is to prefix with "I".  The rationale given is _Makes it easy to differentiate interfaces from regular classes at a glance_ which I'm not arguing with.  The main reason I disagree with the default for this rule is that the [coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names) for _contributors to Typescript` - which you could easily say should be the template for all Typescript coding standards - say not to use "I" as a prefix for interface names.  Additionally, I rarely see libraries, coding examples, etc. that use the "I" prefix.

Our team would like to use all the TSLint defaults, but we're having a hard time with this one...

**Comment by KSXGitHub** [comment] 2018-10-03 17:58
I also find some of `tslint:recommended` rules make no sense, like `"trailing-comma": true` for instance (it changes the way the code behave, both in TS and JS). For that reason, I use other configurations, such as [tslint-config-standard](https://github.com/blakeembrey/tslint-config-standard)

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 18:48
Duplicate of #1520.

**Closed by JoshuaKGoldberg** 2018-11-05 18:48 UTC

**Comment by bfrost2893** [comment] 2018-12-11 21:22
@KSXGitHub how does trailing comma change code behavior?

**Comment by KSXGitHub** [comment] 2018-12-11 23:06
I double checked, I was wrong, sorry.
