### ISSUE TITLE
Allow to exclude imports for no-implicit-package-dependencies

### ISSUE THREAD

**Issue by akosyakov** [palantir/tslint#3736] opened 2018-02-26 13:44 UTC
Theia repo is the mono repo: https://github.com/theia-ide/theia. We manage all dev dependencies in one place in the root package, so they can be used in all packages. I would like to filter out such dependencies for `no-implicit-package-dependencies`.

**Comment by akosyakov** [comment] 2018-02-26 14:05
I would like to work on it? Does it make sense?

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 10:30
Heya @akosyakov - `no-implicit-dependencies` allows a couple of flags for being more permissive:

* `"dev"` indicates to allow devDependencies
* `"optional"` indicates to allow optional dependencies

Do those work for your use case?

```json
{
    "rules": {
        "no-implicit-dependencies": [true, "dev", "optional"]
    }
}
```

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 10:31
Heya @akosyakov - it's a little unclear what you're suggesting here. DO you mean you'd like to make the rule able to look at additional `package.json`s?

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 10:31
Ah, duplicate of #3737. So yes!

**Closed by JoshuaKGoldberg** 2018-11-05 10:31 UTC
Labels: Status: Needs More Info
