### ISSUE TITLE
'expected parameter to have typedef' 

### ISSUE THREAD

**Issue by marknadig** [palantir/tslint#403] opened 2015-05-21 21:47 UTC
Given this code

    var a: string[] = [
      'Hydrogen',
      'Helium',
      'Lithium',
      'Beryllium'
    ];
    
    var a3: number[] = a.map(s => s.length );
    console.log(a3);

the  linter is complaining that s isn't given a typedef. Since a is typed as 'string' array, I was surprised it didn't flow through. 

Changing to     

     var a3: number[] = a.map(s: string => s.length );

makes it happy

**Comment by leeavital** [comment] 2015-06-09 21:15
I'm assuming you're using the typedef:parameter rule?

TSLint doesn't do any type-checking; this is the expected behavior.

One idea is to have two separate rules: typedef:parameter and typedef:arrow for traditional function expressions and arrow functions respectively.

**Comment by adidahiya** [comment] 2015-06-18 21:00
duplicate of #333 -- let's move discussion there

**Closed by adidahiya** 2015-06-18 21:00 UTC
Labels: duplicate
