### ISSUE TITLE
Peer dependency complaint but I'm using typescript@3.1.0-dev.20180907

### ISSUE THREAD

**Issue by jpike88** [palantir/tslint#4184] opened 2018-09-24 08:07 UTC

**Comment by JoshuaKGoldberg** [comment] 2018-11-05 17:53
Related: #1556

In the meantime, should some 3.X peers be allowed?

**Comment by jpike88** [comment] 2019-03-26 03:20
I'm guessing this discussion never got anywhere... this warning is beginning to drive me insane.

**Comment by JoshuaKGoldberg** [comment] 2019-06-16 04:23
😢

Duplicate of #1556.

**Closed by JoshuaKGoldberg** 2019-06-16 04:23 UTC
Labels: Domain: Tooling, P1, Status: In Discussion
