### ISSUE TITLE
Publish a patch release of TSLint

### ISSUE THREAD

**Issue by iclanton** [palantir/tslint#4353] opened 2018-12-08 00:15 UTC
When will the next release of TSLint be published? My team is blocked behind release of this bugfix (https://github.com/palantir/tslint/pull/4295), and because we publish tools for third parties, forking TSLint and publishing it ourselves would be extremely cumbersome.

**Comment by JoshuaKGoldberg** [comment] 2018-12-08 00:18
Duplicate of #4340.

Agreed that this would be nice to have soon! 🙂

**Closed by JoshuaKGoldberg** 2018-12-08 00:18 UTC
Labels: Resolution: Duplicate, Type: Question
