### ISSUE TITLE
Display computed rules list

### ISSUE THREAD

**Issue by dchenk** [palantir/tslint#4698] opened 2019-05-10 03:17 UTC
### Feature request

**Is your feature request that we implement a new rule?**
No.

**Is your feature request related to a problem? Please describe.**
It's often difficult to determine which rules are active and in what configuration. I'm often needing to search through the list of rule sets listed in `extends` to figure out what's being overridden where.

**Describe the solution you'd like**
There should be a CLI command that will display the list of computed rules. The command could be named something like `--display-computed`. If the option is present when `tslint` is invoked, you would simply get a print out in standard output of a JSON array of the resultant rules after combining all the imported and overridden rules.

**Describe alternatives you've considered**
There doesn't appear to be a way to get `tslint` to display precisely how it resolved all the rules given to it.

**Additional context**
ClangFormat has such a feature (named `-dump-config`): https://clang.llvm.org/docs/ClangFormat.html

**Comment by adidahiya** [comment] 2019-05-16 01:26
Yeah, this would be nice to have. Related: https://github.com/palantir/tslint/issues/2267, https://github.com/palantir/tslint/issues/4608, https://github.com/palantir/tslint/issues/3828

**Comment by JoshuaKGoldberg** [comment] 2019-06-16 04:43
I believe this particular issue is duplicate of #3720, which was resolved in #4744. Please do post here if that's not the case!

**Closed by JoshuaKGoldberg** 2019-06-16 04:43 UTC
Labels: P2, Status: Accepting PRs, Type: Feature Request
