### ISSUE TITLE
--fix is working terribly!

### ISSUE THREAD

**Issue by vajahath** [palantir/tslint#2972] opened 2017-06-29 11:19 UTC
### Bug Report

- __TSLint version__: 5.4.3
- __TypeScript version__: 2.4.1
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted

```ts
const config:object = {
	"folder_name": "mocha-insights",
	"coma_replacer": " ~ "
}

export default config;
```

with `tslint.json` configuration:

```json
{
	"defaultSeverity": "error",
	"extends": [
		"tslint:recommended"
	],
	"jsRules": {},
	"rules": {
		"class-name": true,
		"comment-format": [true, "check-space"],
		"eofline": true,
		"forin": true,
		"indent": [true, "tabs"],
		"jsdoc-format": true,
		"label-position": true,
		"no-arg": true,
		"no-conditional-assignment": true,
		"no-construct": true,
		"no-debugger": true,
		"no-duplicate-variable": true,
		"no-empty": true,
		"no-inferrable-types": true,
		"no-internal-module": true,
		"no-shadowed-variable": true,
		"no-switch-case-fall-through": true,
		"no-trailing-whitespace": true,
		"no-unused-expression": true,
		"no-unused-variable": true,
		"no-use-before-declare": true,
		"no-var-keyword": true,
		"quotemark": [true, "single"],
		"radix": true,
		"semicolon": [true, "always"],
		"switch-default": true,
		"triple-equals": [true, "allow-null-check"],
		"variable-name": [true, "check-format", "ban-keywords"],
		"prefer-const": true
	},
	"rulesDirectory": []
}

```

#### Actual behavior
```ts
const config:  object = {
	'folder_name'"m'mocha-insights'	co'coma_replacer'~ ' ~ ',ex;port default config;
```
#### Expected behavior
something that is not terrible as above is expected!!

**Comment by ajafff** [comment] 2017-06-29 11:53
I guess you are using the `--project` flag.
Looks like a duplicate of #2862 and should be fixed by #2864 

@adidahiya please publish a new release with this important bugfix.

**Comment by vajahath** [comment] 2017-06-29 12:20
this is the command I issued to lint:
```
tslint -c tslint.json -p tsconfig.json -t stylish ./src/config/default-config.ts --fix
```

**Comment by ajafff** [comment] 2017-06-29 12:24
Since `-p` is an alias for `--project`, it's exactly like i thought. The fix has already landed and will be shipped with the next release

**Closed** 2017-07-05 17:14 UTC

**Comment by adidahiya** [comment] 2017-07-05 17:16
@ajafff sorry for the delay; I was out on vacation. Will get a v5.5 release out this week.
