### ISSUE TITLE
Warn if disabled lint doesn't fail

### ISSUE THREAD

**Issue by ThomasdenH** [palantir/tslint#4445] opened 2019-01-08 14:54 UTC
### Rule Suggestion

The set of lints used for a project might change over time. It would be nice if TSLint could detect lint surpressions that don't throw in the first place. This could be because the surpression is not relevant to the line/file, or because the surpressed lint is not enabled in the config.

**Comment by JoshuaKGoldberg** [comment] 2019-01-08 14:58
Absolutely agreed! Duplicate of #1330.

**Closed by JoshuaKGoldberg** 2019-01-08 14:58 UTC

**Comment by ThomasdenH** [comment] 2019-01-08 15:11
Whoops!
