### ISSUE TITLE
Bug: no-unnecessary-callback-wrapper exception

### ISSUE THREAD

**Issue by jupl** [palantir/tslint#2808] opened 2017-05-22 12:18 UTC
### Bug Report

- __TSLint version__: 5.2.0
- __TypeScript version__: 2.3.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
const vals = ['a', 'b', 'c']

vals.map(x => doSomething(x))

function doSomething(str: string, opts?: boolean) {
  // do something
}
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "no-unnecessary-callback-wrapper": true
  }
}
```

#### Actual behavior
No lint error

#### Expected behavior
I get a linting error, but I can't change the code to `vals.map(doSomething)` as TypeScript won't compile with the error `Type 'number' is not assignable to type 'boolean'. [2345]`

**Comment by ajafff** [comment] 2017-05-23 08:33
duplicate of #2430

**Closed** 2017-05-23 12:04 UTC
