### ISSUE TITLE
no-unused-variable: All imports unused

### ISSUE THREAD

**Issue by jasekiw** [palantir/tslint#2577] opened 2017-04-15 16:06 UTC
### Bug Report

- __TSLint version__5.1.0:
- __TypeScript version__2.2.1:
- __Running TSLint via__: (pick one) CLI 

#### TypeScript code being linted

```ts
import {Injectable} from "@angular/core";
import {RoutesFactoryContract} from "./RoutesFactoryContract";
/**
 * An environment helper to get fully qualified urls
 */
@Injectable()
export class MockRoutesFactory implements RoutesFactoryContract {

  /**
   * Generates a url given from the environment that is a api url meaning it will contain the api base url.
   * @param {string} url The url with placeholder templates in it. placeholder templates look like this: {id}
   * @param {Object} parameters key to value mapping of placeholder name to the real value. The keys shall not include the {}
   * @return string The rendered url
   */
  public getApiUrl(url: string, parameters?: Object): string {
    return url;
  }

  /**
   * Generates a url given from the environment.
   * @param {string} url The url with placeholder templates in it. placeholder templates look like this: {id}
   * @param {Object} parameters key to value mapping of placeholder name to the real value. The keys shall not include the {}
   * @return string The rendered url
   */
  public getUrl(url: string, parameters?: Object): string {
    return url;
  }

}

```

with `tslint.json` configuration:

```json
{
  "rules": {
    "no-duplicate-variable": true,
    "no-constant-condition": true,
    "no-unused-variable": [
      true
    ]
  },
  "extends": [
    "tslint-eslint-rules"
  ]
}

```
Background:

Ionic 2 project

cli command: `tslint --type-check -c tslint.json --project tsconfig.json`

#### Actual behavior
no-unused-variable reports All imports are unused.
example:
`ERROR: src/providers/routes/MockRoutesFactory.ts[2, 1]: All imports are unused.`
#### Expected behavior
No errors should be found for this file.

**Comment by andy-hanson** [comment] 2017-04-15 17:19
I can't reproduce this in a sample project. Can you try getting an isolated repro?

**Comment by jasekiw** [comment] 2017-04-15 18:03
I am about to post a sample repo to github for this issue.

**Comment by jasekiw** [comment] 2017-04-15 18:18
Here is an example project that exercises the issue.

https://github.com/jasekiw/ionic2-tslint-issue2577

**Comment by andy-hanson** [comment] 2017-04-15 22:28
Here's the problem:

```ts
declare module '*';
```

TypeScript has an issue when using an imported type from this. I've filed Microsoft/TypeScript#15207.
Until then, you could just remove that.

**Comment by jasekiw** [comment] 2017-04-15 22:43
Hi andy,

I removed that code and it still seems to be throwing "All imports are unused". Is there anything else that could be causing it?

**Comment by andy-hanson** [comment] 2017-04-15 22:49
Are you getting:
```
ERROR: src/providers/routes/RoutesFactory.ts[4, 1]: All imports are unused.
```

Because that one's (importing `Platform` on line 4) is actually unused...

**Comment by jasekiw** [comment] 2017-04-15 23:03
Right, I put that in there to show what goes wrong.

There is one unused import, the other three however are used. 
that means
```
ERROR: src/providers/routes/RoutesFactory.ts[4, 1]: All imports are unused.
```

is a false statement.

**Comment by andy-hanson** [comment] 2017-04-15 23:10
Would you prefer:
```
src/providers/routes/RoutesFactory.ts[4, 1]: All imports on this line are unused.
```

**Comment by jasekiw** [comment] 2017-04-15 23:19
Interesting it looks like the wording was just changed between versions 3.15.1 and 5.1.0. 
I didn't realize that and thought it was throwing the same error as before.

in 3.15.1 it would throw this error instead 

```
src/providers/routes/RoutesFactory.ts[4, 24]: Unused import: 'Platform'
```

I believe this error now is fine it's just not as verbose.

**Comment by jasekiw** [comment] 2017-04-15 23:35
However this does break support for WebStorm. There is no longer linking in the results window. I shall open an issue with them.

**Comment by amatiasq** [comment] 2017-05-22 13:06
I'm having this issue too but can't isolate it: `ERROR: src/pathfinding/pathfinding.spec.ts[7, 1]: All imports are unused.`

These are the first 7 lines of the offending file:

```
import { assert } from 'chai';
import { Vector3D } from '../core/vector3d';
import { AStar } from './a-star';
import { Area } from './area';
import { INode } from './node';
import { Pathfinding } from './pathfinding';
import { ITile } from './tile';
```

All imports are used, I tried removing all the imports and adding back only the ones used but it still complaining.

On a different file I have `import * as sinon from 'sinon';` which is throwing the same error `ERROR: src/pathfinding/area.spec.ts[5, 1]: All imports are unused.`. I can understand this one but not the previous one.

My `tsconfig.json` file

```
{
  "include": [ "src/**/*.ts" ],
  "exclude": [ "node_modules" ],

  "compilerOptions": {
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es6"
  }
}
```

**Comment by andy-hanson** [comment] 2017-05-23 00:07
@amatiasq Can't help without knowing the rest of the file. It may be another case of Microsoft/TypeScript#14953.

**Comment by amatiasq** [comment] 2017-05-23 08:51
@andy-hanson I've finally isolated the issue and it's not easy to catch: https://gist.github.com/amatiasq/7352f52d9290311589e3df5bc2afc1fe

Let me copy the readme description from the gist:

## Bug in TSLint `no-unused-variable` rule.

### How to reproduce

If you run `tslint -c tslint.json --type-check --project tsconfig.json '*.ts'` in this folder you'll see:

```bash
$ tslint -c tslint.json --type-check --project tsconfig.json '*.ts'
ERROR: main.ts[1, 1]: All imports are unused.
```

### Conditions

- If you remove any of the files in this project (including `fa.ts` which is not used at all) the error disappears.
- If you rename `fa.ts` to something after `foo.ts` (like `h.ts`, `fz.ts` or even `fop.ts`) the error disappears.
- If you rename `fa.ts` to something before `foo.ts` (like `a.ts` or `fon.ts`) the error remains
- If you empty `fa.ts` the error disappears
- If you replace remove `Foo` import from `main.ts` and replace `Foo<IBar>` for `Array<IBar>` or `Partial<IBar>` the error disappears
- And of course if your remove `IBar` import from `main.ts` and replace `Foo<IBar>` for `Foo<{}>` or something else the error disappears

#### TSLint version

5.2.0

**Comment by andy-hanson** [comment] 2017-05-24 02:04
@amatiasq Fixed in `typescript@next`. Looks like case https://github.com/Microsoft/TypeScript/issues/14953#issuecomment-302101264.

**Comment by amatiasq** [comment] 2017-05-24 07:58
@andy-hanson Are you sure? all imports in the gist are valid :\

**Comment by andy-hanson** [comment] 2017-05-24 23:42
The imports may not be valid from within the no-unused-variable rule's perspective because it uses a fake project. I tested it, tell me if you're able to reproduce it using the latest tslint and typescript.

**Comment by amatiasq** [comment] 2017-05-25 07:46
What do you mean with fake project? This started as a real project, I just removed the code than didn't make the bug disappear. Anyway with the last version of tslint it doesn't happen anymore.

**Comment by andy-hanson** [comment] 2017-05-25 23:46
I'm referring to the [implementation](https://github.com/palantir/tslint/blob/3088a2d76ba48b80d473f2130f912c28b8570e32/src/rules/noUnusedVariableRule.ts#L369).

**Comment by csvn** [comment] 2017-06-01 10:52
I had the same issue when a type/interface was only used inside a generic (e.g. `Resolve<User>`). 
https://github.com/Microsoft/TypeScript/issues/14953#issuecomment-302101264

Upgrading to `typescript@next` (>=v2.4) made the problem go away for me.

**Comment by adidahiya** [comment] 2017-06-01 16:07
@csvn that's a duplicate of https://github.com/palantir/tslint/issues/2470

**Comment by corydeppen** [comment] 2017-06-29 23:22
I'm running into the same issue using tslint 5.4.3 and tsc 2.4.1.

**Comment by JoshuaKGoldberg** [comment] 2018-11-04 01:08
@aneilbaboo @amatiasq I'm not able to reproduce these errors locally from the gist or what's posted in this thread. `no-unused-variable` is deprecated for TypeScript>=2.9. Closing this issue as non-actionable on our end; if you do still have errors around unused variables and imports/exports, please file them on TypeScript.

**Closed by JoshuaKGoldberg** 2018-11-04 01:08 UTC
Labels: Status: In Discussion

**Comment by JoshuaKGoldberg** [comment] 2020-09-15 21:08
🤖 Beep boop! 👉  **TSLint is deprecated** 👈  and you should **switch to [typescript-eslint](https://typescript-eslint.io)**! 🤖 

🔒 This issue is being locked to prevent further unnecessary discussions. Thank you! 👋
