### ISSUE TITLE
Feature request, check if promise rejection handling is being implemented

### ISSUE THREAD

**Issue by nschurmann** [palantir/tslint#1399] opened 2016-07-13 16:15 UTC
Right now tslint doesn't have an implementation to check if a `catch` is being added to a promise. It would be awesome if it could check for any missing promise catch implementation.

#### TypeScript code being linted

```ts
const P = () =>
    new Promise((resolve, reject) => {
        const x = Math.random() * 100
        if (x < 50) 
            resolve(x)
        reject(x)
    })

P()
    .then(console.log)
```

#### Expected behavior

Promise rejection not implemented

**Comment by adidahiya** [comment] 2016-07-14 00:58
Looks like a duplicate of #744

**Closed by adidahiya** 2016-07-14 00:58 UTC
