### ISSUE TITLE
Left hand side of For...of cannot use type annotation, but tslint requires it

### ISSUE THREAD

**Issue by BrandonCKrueger** [palantir/tslint#786] opened 2015-11-09 15:26 UTC
When using the TypeScript `for...of` loop, TSLint throws a typedef error expecting the first variable to have a type definition, however that is not allowed in TypeScript.

Sample:
```javascript
let names: string[] = [...]
for (let name in names) {
    ...
}
```

TSLint wants `name` to have a typedef, however that is not allowed in TypeScript.

**Comment by adidahiya** [comment] 2015-11-09 16:32
duplicate of #743

**Closed by adidahiya** 2015-11-09 16:32 UTC
