### ISSUE TITLE
Exception in `no-redundant-jsdoc`

### ISSUE THREAD

**Issue by manu-st** [palantir/tslint#3424] opened 2017-10-31 00:29 UTC
### Bug Report

- __TSLint version__: 5.8
- __TypeScript version__: 2.5.3
- __Running TSLint via__: CLI 

#### TypeScript code being linted

```ts
/**
 * Desc.
 *
 * @class Simple
 */
export class Simple
{
   /**
    * Name.
    *
    * @memberof Simple
    */
   name: string;
}
```

with `tslint.json` configuration:

```json
{
   "rules":
   {
       "no-redundant-jsdoc": true
   }
}
```

#### Actual behavior
```
Error: Unexpected tag kind: JSDocClassTag
    at checkTag (C:\Dev\node_modules\tslint\lib\rules\noRedundantJsdocRule.js:99:23)
    at cb (C:\Dev\node_modules\tslint\lib\rules\noRedundantJsdocRule.js:62:25)
    at Array.forEach (<anonymous>)
    at walk (C:\Dev\node_modules\tslint\lib\rules\noRedundantJsdocRule.js:55:34)
    at Rule.AbstractRule.applyWithFunction (C:\Dev\node_modules\tslint\lib\language\rule\abstractRule.js:39:9)
    at Rule.apply (C:\Dev\node_modules\tslint\lib\rules\noRedundantJsdocRule.js:35:21)
    at Linter.applyRule (C:\Dev\node_modules\tslint\lib\linter.js:177:29)
    at C:\Dev\node_modules\tslint\lib\linter.js:119:85
    at Object.flatMap (C:\Dev\node_modules\tslint\lib\utils.js:151:29)
    at Linter.getAllFailures (C:\Dev\node_modules\tslint\lib\linter.js:119:32)
```
#### Expected behavior
```
ERROR: C:/Dev/Simple.ts[4, 4]: JSDoc tag '@class' is redundant in TypeScript code.
ERROR: C:/Dev/Simple.ts[11, 8]: JSDoc tag '@memberof' is redundant in TypeScript code.
```

**Comment by ajafff** [comment] 2017-10-31 11:22
Duplicate of #3413
I already submitted a PR to fix this

**Closed by ajafff** 2017-10-31 11:22 UTC
