### ISSUE TITLE
Generate changelog from commit messages

### ISSUE THREAD

**Issue by JKillian** [palantir/tslint#1500] opened 2016-08-19 19:38 UTC
Writing up the changelog for each release takes a non-trivial amount of time. It would be useful if we autogenerated it based off of commit messages and commit authors. Commit messages would have to follow our standard changelog format, but this is easy given the "squash and merge" GH feature. Commits that started with [trivial] or [docs] or other tags could be automatically ignored.

**Comment by adidahiya** [comment] 2017-02-01 15:19
closing as duplicate of the more up-to-date #2032

**Closed by adidahiya** 2017-02-01 15:19 UTC
Labels: Domain: Tooling, P2
