### ISSUE TITLE
How can I set '--project xxx' in the tslint.json?

### ISSUE THREAD

**Issue by chenxxzhe** [palantir/tslint#2844] opened 2017-05-29 17:28 UTC
I use `SublimeLinter-contrib-tslint` and it is difficult to set the `--project` in the `sublimeLinter.sublime-settings`, to be more precise, i don't know how to set the path of `tsconfig.json` in this setting.

How can i set the `project` property just in the `tslint.json` ?

**Comment by adidahiya** [comment] 2017-05-30 16:59
essentially a duplicate of https://github.com/palantir/tslint/issues/2227

**Closed by adidahiya** 2017-05-30 16:59 UTC
