### ISSUE TITLE
Prefer function type properties over interface methods

### ISSUE THREAD

**Issue by ulrichb** [palantir/tslint#4302] opened 2018-11-19 17:40 UTC
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

General problem

**What does your suggested rule do?**

Interface declarations should not contain methods but properties with function types instead.

E.g. Prefer `interface InterfaceWithField { someFunc: (p: string | number) => void; }` 
over `interface InterfaceWithMethod { someFunc(p: string | number): void; }`

Reasons
1. Type safety: Even with `--strictFunctionTypes` TSC does bivariant checks for interface methods. See the following example where this introduces a bug, which would result in an compile error when fields are used.<br>
From the TSC handbook: ["Under --strictFunctionTypes the first assignment is still permitted if compare was declared as a method. Effectively, T is bivariant in Comparer<T> because it is used only in method parameter positions"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html)

1. Fields can be declared with a `readonly` modifier; methods are implicitly writeable

**List several examples where your rule could be used**
* Example with a union type (`string | number`)
```ts
interface InterfaceWithMethod {
    someFunc(p: string | number): void;
}

const a: InterfaceWithMethod = {
    // HERE TSC does a bivariant check => no compilation error ...
    someFunc(p: string) {
        // ...but `p` could be a number => run-time error
        console.log(p.toUpperCase()); 
     },
};
try { a.someFunc(42); } catch (e) { alert(e) }

//

interface InterfaceWithField {
    someFunc: (p: string | number) => void;
}

const b: InterfaceWithField = {
    // HERE TSC (with enabled --strictFunctionTypes) emits
    // "Type 'string |number' is not assignable to type 'string'":
    someFunc(p: string) { },
};
```
* The same applies to `null`/`undefined` with using --strictNullChecks` when the interface parameter type contains them.

**Comment by JoshuaKGoldberg** [comment] 2018-11-19 21:16
Duplicate of #4240.

**Closed by JoshuaKGoldberg** 2018-11-19 21:16 UTC
