### ISSUE TITLE
tslint produces 0 error code even if errors are present

### ISSUE THREAD

**Issue by bepremeg** [palantir/tslint#4359] opened 2018-12-10 14:51 UTC
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.6
- __Running TSLint via__: npx/npm

#### TypeScript code being linted

```ts
// really broken code to force an unfixable error
 const tr ig ger = new rx.ReplaySubject<[number, number]>();
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint-config-prettier"
  ],
  "rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/tslint-defocus/dist",
    "tslint-plugin-prettier"
  ],
  ...
}
```

#### Actual behavior

When running
```bash
 $ npx tslint --project projects/ng-kaart/tsconfig.lib.json ; echo $?
The 'prettier' rule threw an error in '/home/gpremer/src/awv/kaart/projects/ng-kaart/src/lib/util/exponential-timer.ts':
SyntaxError: ',' expected. (5:14)
  3 | export function exponentialTimer(firstDelay: number, periodBase: number): rx.Observable<number> {
  4 |   return rx.Observable.create(observer => {
> 5 |     const tr ig ger = new rx.ReplaySubject<[number, number]>();
    |              ^
  6 |     const subscription1 = rx.timer(firstDelay).subscribe(() => trigger.next([1, 0]));
  7 |     const subscription2 = trigger.subscribe(([delay, n]) => {
  8 |       observer.next(n);
    at e (/home/gpremer/src/awv/kaart/node_modules/prettier/parser-typescript.js:1:329)
    at Object.parse (/home/gpremer/src/awv/kaart/node_modules/prettier/parser-typescript.js:1:2010001)
    at Object.parse$2 [as parse] (/home/gpremer/src/awv/kaart/node_modules/prettier/index.js:7138:19)
    at coreFormat (/home/gpremer/src/awv/kaart/node_modules/prettier/index.js:10398:23)
    at format (/home/gpremer/src/awv/kaart/node_modules/prettier/index.js:10570:16)
    at formatWithCursor (/home/gpremer/src/awv/kaart/node_modules/prettier/index.js:10582:12)
    at /home/gpremer/src/awv/kaart/node_modules/prettier/index.js:34924:15
    at Object.format (/home/gpremer/src/awv/kaart/node_modules/prettier/index.js:34943:12)
    at Walker.walk (/home/gpremer/src/awv/kaart/node_modules/tslint-plugin-prettier/rules/prettierRule.js:54:34)
    at Rule.AbstractRule.applyWithWalker (/home/gpremer/src/awv/kaart/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
0
```
I.e. the exit code is 0.

There is no '--force' in any of my configuration files.

#### Expected behavior
The exit code should be 1

This breaks the integration as a pre-commit hook.

**Comment by JoshuaKGoldberg** [comment] 2018-12-11 05:32
Duplicate of #3949. Agreed!

**Closed by JoshuaKGoldberg** 2018-12-11 05:32 UTC
