### ISSUE TITLE
New rule for forbidding whitespaces in one-line brackets

### ISSUE THREAD

**Issue by lmoe** [palantir/tslint#1698] opened 2016-11-08 09:44 UTC
- __TSLint version__: 3.15.1
- __TypeScript version__: 1.0.1.0
- __Running TSLint via__: Visual Studio Code

#### TypeScript code being linted

```ts
import { Foo, Bar } from 'baz'
```

#### Expected behavior

I want to lint the brackets in a one-line to have no spaces at the beginning and at the end resulting in

```ts
import {Foo, Bar} from 'baz'
```

It does not seem like tslint has such a rule and I would like to see it in there.

**Comment by CarsonF** [comment] 2016-12-20 23:58
And I would like it for the opposite reason 👍

**Comment by adidahiya** [comment] 2016-12-21 03:25
looks like a duplicate of #1044

**Closed by adidahiya** 2016-12-21 03:25 UTC
