### ISSUE TITLE
`unused variable` error while accessing imports in `export` statement

### ISSUE THREAD

**Issue by zdychacek** [palantir/tslint#818] opened 2015-11-24 10:17 UTC
Hi,

I am getting following error when linting this code:

Code:
```ts
import A from './a;
import B from './b';

export { A, B };
```

Errors:
```
[1, 8]: unused variable: 'A'
[2, 8]: unused variable: 'B'
```

Using `tslint v3.0.0`.

O.

**Comment by zdychacek** [comment] 2015-11-24 11:09
This problem does not apply exclusively to `export` statement.

Code:

```
import a from './a';
const obj = { a };
```

Error:

```
[1, 8]: unused variable: 'a'
```

O.

**Comment by JKillian** [comment] 2015-12-18 16:14
Hi @zdychacek, thanks for the report. This is a duplicate of #684, so I'm going to close this issue. This is something that should be solved though!

**Closed** 2016-01-12 05:53 UTC
Labels: Resolution: Duplicate
