### ISSUE TITLE
Option for "variable-name" rule to allow leading underscore for property backing fields

### ISSUE THREAD

**Issue by glen-84** [palantir/tslint#1489] opened 2016-08-17 13:05 UTC
It would be nice to have this:

``` ts
class Example {
    private _var1; // ERROR, not a backing field, shouldn't start with an underscore.
    private _var2; // Allowed, as it's a backing field for the `var2` property.

    public get var2() {
        return this._var2;
    }
}
```

`allow-leading-underscore-backing-fields` maybe.

Edit: It would be considered a backing field if there was either a getter or a setter with the same name (sans the leading underscore).

**Comment by stevedenman** [comment] 2016-09-20 02:50
This naming convention for backing fields is also suggested [in the typescript handbook ](https://www.typescriptlang.org/docs/handbook/classes.html#accessors);

    private _fullName: string;

    get fullName(): string {
        return this._fullName;
    }

**Comment by JoshuaKGoldberg** [comment] 2018-11-03 19:00
`variable-name` now allows options such as `"allow-leading-underscore"`. 🎉

**Comment by glen-84** [comment] 2018-11-03 20:37
@JoshuaKGoldberg That's not new, and allows leading underscores on *any* variable.

**Comment by JoshuaKGoldberg** [comment] 2018-11-03 20:43
Oh! My apologies, I speed-read the rule and missed the difference. Agreed that an option to allow a leading underscore _only_ for backing properties would be nice.

We should note that it shouldn't be allowed to be enabled at the same time as `"allow-leading-underscore"`.

**Comment by Xenya0815** [comment] 2019-02-05 14:23
The issue is closed but I can't find a option at the documentation. Is it still planned to offer a option like `allow-leading-underscore-backing-fields`?

**Comment by JoshuaKGoldberg** [comment] 2019-02-05 15:22
Thanks for the catch @Xenya0815 - this should have been re-opened.

**Comment by adidahiya** [comment] 2019-09-10 17:08
Closing in favor of https://github.com/typescript-eslint/typescript-eslint/issues/816

**Closed by adidahiya** 2019-09-10 17:08 UTC
Labels: P2, Status: Accepting PRs, Type: Enhancement

**Comment by JoshuaKGoldberg** [comment] 2020-03-20 18:08
🤖 Beep boop! 👉  **TSLint is deprecated** 👈 _(#4534)_  and you should **switch to [typescript-eslint](https://typescript-eslint.io)**! 🤖 

🔒 This issue is being locked to prevent further unnecessary discussions. Thank you! 👋
