### ISSUE TITLE
Configure no-null-keyword

### ISSUE THREAD

**Issue by usernamehw** [palantir/tslint#3229] opened 2017-09-16 01:51 UTC
It would be cool to add an exception to rule [no-null-keyword](https://palantir.github.io/tslint/rules/no-null-keyword/) allowing you to use Object as a map (without Prototype).

`Object.create()` first parameter is either null or object:

```javascript
// currently error (or whatever set in severity level)
const map = Object.create(null);
//                        ^^^^ Use 'undefined' instead of 'null'
```

**Comment by ajafff** [comment] 2017-09-17 07:23
Looks like a duplicate of #2798

**Comment by adidahiya** [comment] 2017-09-18 23:08
Agreed; I would like to see a more general solution to the problem as outlined in #2798

**Closed by adidahiya** 2017-09-18 23:08 UTC
