### ISSUE TITLE
Spurious unused variable when used via extends

### ISSUE THREAD

**Issue by ef4** [palantir/tslint#721] opened 2015-10-09 06:33 UTC
This gives an unused variable warning for `Parent`:

```ts
let Parent = class {};
class Child extends Parent {}
```

**Comment by JKillian** [comment] 2015-10-09 14:44
Thanks for the report @ef4! I believe this is primarily caused by a TypeScript issue (see the issue referenced above) so as soon as it gets fixed in TS we'll be able to resolve it here.

**Comment by JKillian** [comment] 2015-10-09 19:03
@ef4 This should actually be fixed if you use the `next` version of TSLint. Try it and see if the problem persists?

**Comment by ef4** [comment] 2015-10-09 19:14
I can confirm that this is fixed in tslint@next. Thanks!

**Closed** 2015-10-09 19:33 UTC
Labels: P1, Resolution: Fixed, Type: Bug
