### ISSUE TITLE
no-switch-case-fall-through false positive when using curly braces

### ISSUE THREAD

**Issue by isaacplmann** [palantir/tslint#954] opened 2016-02-03 19:38 UTC
When a case block is enclosed in curly braces, no-switch-case-fall-through mistakenly reports an error.

Example:

      case JobState.DependencyWait:
        {
          this.m_Description = 'Waiting for Dependencies.';
          break;
        }

      case JobState.Held:

This should be a slightly easier issue to fix than Issue #950

**Comment by JKillian** [comment] 2016-02-04 21:17
Because [the TypeScript compiler recently introduced a `--noFallthroughCasesInSwitch` flag](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#case-clause-fall-throughs) this rule will most likely soon be deprecated.

**Comment by JKillian** [comment] 2016-02-04 21:19
Ah, and in fact, this is a duplicate of #785. Thanks for the bug report though @isaacplmann, let us know if you encounter any others!

**Closed by JKillian** 2016-02-04 21:19 UTC
Labels: P3, Resolution: Duplicate, Type: Bug
