### ISSUE TITLE
no-unused-variable false positive when let/const is declared in a require statement

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#504] opened 2015-07-15 15:14 UTC
this code incorrectly reports that `fs` is unused:

```ts
let fs = require("fs"); // failure

fs.readFileSync("test.ts");
```

replacing `let` with `const` results in the same failure.

**Comment by leeavital** [comment] 2015-07-15 15:24
Duplicate of #325, which is due to a problem in language services.

**Comment by adidahiya** [comment] 2015-07-17 01:33
I just tried it out and this bug + #325 are fixed with TS v1.5.3

**Closed** 2015-07-17 01:34 UTC
Labels: Resolution: Duplicate, Type: Bug
